// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/v1/kube/kube_api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkloadKind int32

const (
	WorkloadKind_WORKLOAD_KIND_UNKNOWN      WorkloadKind = 0
	WorkloadKind_WORKLOAD_KIND_DEPLOYMENT   WorkloadKind = 1
	WorkloadKind_WORKLOAD_KIND_REPLICA_SET  WorkloadKind = 2
	WorkloadKind_WORKLOAD_KIND_STATEFUL_SET WorkloadKind = 3
	WorkloadKind_WORKLOAD_KIND_DAEMON_SET   WorkloadKind = 4
	WorkloadKind_WORKLOAD_KIND_JOB          WorkloadKind = 5
	WorkloadKind_WORKLOAD_KIND_CRONJOB      WorkloadKind = 6
	WorkloadKind_WORKLOAD_KIND_POD          WorkloadKind = 7
)

// Enum value maps for WorkloadKind.
var (
	WorkloadKind_name = map[int32]string{
		0: "WORKLOAD_KIND_UNKNOWN",
		1: "WORKLOAD_KIND_DEPLOYMENT",
		2: "WORKLOAD_KIND_REPLICA_SET",
		3: "WORKLOAD_KIND_STATEFUL_SET",
		4: "WORKLOAD_KIND_DAEMON_SET",
		5: "WORKLOAD_KIND_JOB",
		6: "WORKLOAD_KIND_CRONJOB",
		7: "WORKLOAD_KIND_POD",
	}
	WorkloadKind_value = map[string]int32{
		"WORKLOAD_KIND_UNKNOWN":      0,
		"WORKLOAD_KIND_DEPLOYMENT":   1,
		"WORKLOAD_KIND_REPLICA_SET":  2,
		"WORKLOAD_KIND_STATEFUL_SET": 3,
		"WORKLOAD_KIND_DAEMON_SET":   4,
		"WORKLOAD_KIND_JOB":          5,
		"WORKLOAD_KIND_CRONJOB":      6,
		"WORKLOAD_KIND_POD":          7,
	}
)

func (x WorkloadKind) Enum() *WorkloadKind {
	p := new(WorkloadKind)
	*p = x
	return p
}

func (x WorkloadKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_kube_kube_api_proto_enumTypes[0].Descriptor()
}

func (WorkloadKind) Type() protoreflect.EnumType {
	return &file_api_v1_kube_kube_api_proto_enumTypes[0]
}

func (x WorkloadKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadKind.Descriptor instead.
func (WorkloadKind) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{0}
}

type GetClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoRequest) Reset() {
	*x = GetClusterInfoRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoRequest) ProtoMessage() {}

func (x *GetClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{0}
}

type GetClusterInfoResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	PodsCidr    []string               `protobuf:"bytes,1,rep,name=pods_cidr,json=podsCidr,proto3" json:"pods_cidr,omitempty"`
	ServiceCidr []string               `protobuf:"bytes,2,rep,name=service_cidr,json=serviceCidr,proto3" json:"service_cidr,omitempty"`
	NodeCidr    []string               `protobuf:"bytes,4,rep,name=node_cidr,json=nodeCidr,proto3" json:"node_cidr,omitempty"`
	VpcCidr     []string               `protobuf:"bytes,5,rep,name=vpc_cidr,json=vpcCidr,proto3" json:"vpc_cidr,omitempty"`
	// other_cidr is a list of known cloud services CIDRs
	OtherCidr     []string `protobuf:"bytes,3,rep,name=other_cidr,json=otherCidr,proto3" json:"other_cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoResponse) Reset() {
	*x = GetClusterInfoResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoResponse) ProtoMessage() {}

func (x *GetClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetClusterInfoResponse) GetPodsCidr() []string {
	if x != nil {
		return x.PodsCidr
	}
	return nil
}

func (x *GetClusterInfoResponse) GetServiceCidr() []string {
	if x != nil {
		return x.ServiceCidr
	}
	return nil
}

func (x *GetClusterInfoResponse) GetNodeCidr() []string {
	if x != nil {
		return x.NodeCidr
	}
	return nil
}

func (x *GetClusterInfoResponse) GetVpcCidr() []string {
	if x != nil {
		return x.VpcCidr
	}
	return nil
}

func (x *GetClusterInfoResponse) GetOtherCidr() []string {
	if x != nil {
		return x.OtherCidr
	}
	return nil
}

type GetIPInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPInfoRequest) Reset() {
	*x = GetIPInfoRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPInfoRequest) ProtoMessage() {}

func (x *GetIPInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIPInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetIPInfoRequest) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

type GetIPInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *IPInfo                `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPInfoResponse) Reset() {
	*x = GetIPInfoResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPInfoResponse) ProtoMessage() {}

func (x *GetIPInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIPInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetIPInfoResponse) GetInfo() *IPInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type GetIPsInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ips           [][]byte               `protobuf:"bytes,1,rep,name=ips,proto3" json:"ips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPsInfoRequest) Reset() {
	*x = GetIPsInfoRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPsInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPsInfoRequest) ProtoMessage() {}

func (x *GetIPsInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPsInfoRequest.ProtoReflect.Descriptor instead.
func (*GetIPsInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetIPsInfoRequest) GetIps() [][]byte {
	if x != nil {
		return x.Ips
	}
	return nil
}

type GetIPsInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*IPInfo              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIPsInfoResponse) Reset() {
	*x = GetIPsInfoResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIPsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIPsInfoResponse) ProtoMessage() {}

func (x *GetIPsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIPsInfoResponse.ProtoReflect.Descriptor instead.
func (*GetIPsInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{5}
}

func (x *GetIPsInfoResponse) GetList() []*IPInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type IPInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodUid        string                 `protobuf:"bytes,1,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodName       string                 `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,4,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	WorkloadKind  string                 `protobuf:"bytes,5,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	WorkloadUid   string                 `protobuf:"bytes,6,opt,name=workload_uid,json=workloadUid,proto3" json:"workload_uid,omitempty"`
	Zone          string                 `protobuf:"bytes,7,opt,name=zone,proto3" json:"zone,omitempty"`
	Region        string                 `protobuf:"bytes,10,opt,name=region,proto3" json:"region,omitempty"`
	NodeName      string                 `protobuf:"bytes,8,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	CloudDomain   string                 `protobuf:"bytes,11,opt,name=cloud_domain,json=cloudDomain,proto3" json:"cloud_domain,omitempty"`
	Ip            []byte                 `protobuf:"bytes,9,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPInfo) Reset() {
	*x = IPInfo{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPInfo) ProtoMessage() {}

func (x *IPInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPInfo.ProtoReflect.Descriptor instead.
func (*IPInfo) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{6}
}

func (x *IPInfo) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *IPInfo) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *IPInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *IPInfo) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *IPInfo) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *IPInfo) GetWorkloadUid() string {
	if x != nil {
		return x.WorkloadUid
	}
	return ""
}

func (x *IPInfo) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *IPInfo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *IPInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *IPInfo) GetCloudDomain() string {
	if x != nil {
		return x.CloudDomain
	}
	return ""
}

func (x *IPInfo) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

type GetPodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uid           string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodRequest) Reset() {
	*x = GetPodRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodRequest) ProtoMessage() {}

func (x *GetPodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodRequest.ProtoReflect.Descriptor instead.
func (*GetPodRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{7}
}

func (x *GetPodRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

type GetPodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pod           *Pod                   `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPodResponse) Reset() {
	*x = GetPodResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPodResponse) ProtoMessage() {}

func (x *GetPodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPodResponse.ProtoReflect.Descriptor instead.
func (*GetPodResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetPodResponse) GetPod() *Pod {
	if x != nil {
		return x.Pod
	}
	return nil
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkloadUid   string                 `protobuf:"bytes,1,opt,name=workload_uid,json=workloadUid,proto3" json:"workload_uid,omitempty"`
	WorkloadName  string                 `protobuf:"bytes,2,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	WorkloadKind  WorkloadKind           `protobuf:"varint,3,opt,name=workload_kind,json=workloadKind,proto3,enum=kube.v1.WorkloadKind" json:"workload_kind,omitempty"`
	Zone          string                 `protobuf:"bytes,4,opt,name=zone,proto3" json:"zone,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	NodeName      string                 `protobuf:"bytes,5,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{9}
}

func (x *Pod) GetWorkloadUid() string {
	if x != nil {
		return x.WorkloadUid
	}
	return ""
}

func (x *Pod) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *Pod) GetWorkloadKind() WorkloadKind {
	if x != nil {
		return x.WorkloadKind
	}
	return WorkloadKind_WORKLOAD_KIND_UNKNOWN
}

func (x *Pod) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *Pod) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type GetNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeRequest) Reset() {
	*x = GetNodeRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeRequest) ProtoMessage() {}

func (x *GetNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeRequest.ProtoReflect.Descriptor instead.
func (*GetNodeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetNodeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeResponse) Reset() {
	*x = GetNodeResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeResponse) ProtoMessage() {}

func (x *GetNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeResponse.ProtoReflect.Descriptor instead.
func (*GetNodeResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{11}
}

func (x *GetNodeResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{12}
}

func (x *Node) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Node) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type GetNodeStatsSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatsSummaryRequest) Reset() {
	*x = GetNodeStatsSummaryRequest{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatsSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatsSummaryRequest) ProtoMessage() {}

func (x *GetNodeStatsSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatsSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatsSummaryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{13}
}

func (x *GetNodeStatsSummaryRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type GetNodeStatsSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *NodeStats             `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatsSummaryResponse) Reset() {
	*x = GetNodeStatsSummaryResponse{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatsSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatsSummaryResponse) ProtoMessage() {}

func (x *GetNodeStatsSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatsSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetNodeStatsSummaryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{14}
}

func (x *GetNodeStatsSummaryResponse) GetNode() *NodeStats {
	if x != nil {
		return x.Node
	}
	return nil
}

type NodeStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeName         string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	StartTimeSeconds int64                  `protobuf:"varint,2,opt,name=start_time_seconds,json=startTimeSeconds,proto3" json:"start_time_seconds,omitempty"`
	Cpu              *CPUStats              `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory           *MemoryStats           `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	Network          *NetworkStats          `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	Fs               *FsStats               `protobuf:"bytes,6,opt,name=fs,proto3" json:"fs,omitempty"`
	Runtime          *RuntimeStats          `protobuf:"bytes,7,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NodeStats) Reset() {
	*x = NodeStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStats) ProtoMessage() {}

func (x *NodeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStats.ProtoReflect.Descriptor instead.
func (*NodeStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{15}
}

func (x *NodeStats) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeStats) GetStartTimeSeconds() int64 {
	if x != nil {
		return x.StartTimeSeconds
	}
	return 0
}

func (x *NodeStats) GetCpu() *CPUStats {
	if x != nil {
		return x.Cpu
	}
	return nil
}

func (x *NodeStats) GetMemory() *MemoryStats {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *NodeStats) GetNetwork() *NetworkStats {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *NodeStats) GetFs() *FsStats {
	if x != nil {
		return x.Fs
	}
	return nil
}

func (x *NodeStats) GetRuntime() *RuntimeStats {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type CPUStats struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds          int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	UsageNanocores       uint64                 `protobuf:"varint,2,opt,name=usage_nanocores,json=usageNanocores,proto3" json:"usage_nanocores,omitempty"`
	UsageCoreNanoseconds uint64                 `protobuf:"varint,3,opt,name=usage_core_nanoseconds,json=usageCoreNanoseconds,proto3" json:"usage_core_nanoseconds,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CPUStats) Reset() {
	*x = CPUStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CPUStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CPUStats) ProtoMessage() {}

func (x *CPUStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CPUStats.ProtoReflect.Descriptor instead.
func (*CPUStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{16}
}

func (x *CPUStats) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *CPUStats) GetUsageNanocores() uint64 {
	if x != nil {
		return x.UsageNanocores
	}
	return 0
}

func (x *CPUStats) GetUsageCoreNanoseconds() uint64 {
	if x != nil {
		return x.UsageCoreNanoseconds
	}
	return 0
}

type MemoryStats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds     int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	AvailableBytes  uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	UsageBytes      uint64                 `protobuf:"varint,3,opt,name=usage_bytes,json=usageBytes,proto3" json:"usage_bytes,omitempty"`
	WorkingSetBytes uint64                 `protobuf:"varint,4,opt,name=working_set_bytes,json=workingSetBytes,proto3" json:"working_set_bytes,omitempty"`
	RssBytes        uint64                 `protobuf:"varint,5,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	PageFaults      uint64                 `protobuf:"varint,6,opt,name=page_faults,json=pageFaults,proto3" json:"page_faults,omitempty"`
	MajorPageFaults uint64                 `protobuf:"varint,7,opt,name=major_page_faults,json=majorPageFaults,proto3" json:"major_page_faults,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryStats) Reset() {
	*x = MemoryStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryStats) ProtoMessage() {}

func (x *MemoryStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryStats.ProtoReflect.Descriptor instead.
func (*MemoryStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{17}
}

func (x *MemoryStats) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *MemoryStats) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *MemoryStats) GetUsageBytes() uint64 {
	if x != nil {
		return x.UsageBytes
	}
	return 0
}

func (x *MemoryStats) GetWorkingSetBytes() uint64 {
	if x != nil {
		return x.WorkingSetBytes
	}
	return 0
}

func (x *MemoryStats) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *MemoryStats) GetPageFaults() uint64 {
	if x != nil {
		return x.PageFaults
	}
	return 0
}

func (x *MemoryStats) GetMajorPageFaults() uint64 {
	if x != nil {
		return x.MajorPageFaults
	}
	return 0
}

type NetworkStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds   int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,3,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,5,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkStats) Reset() {
	*x = NetworkStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkStats) ProtoMessage() {}

func (x *NetworkStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkStats.ProtoReflect.Descriptor instead.
func (*NetworkStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{18}
}

func (x *NetworkStats) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *NetworkStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkStats) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *NetworkStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkStats) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

type FsStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds    int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	AvailableBytes uint64                 `protobuf:"varint,2,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	CapacityBytes  uint64                 `protobuf:"varint,3,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes      uint64                 `protobuf:"varint,4,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
	InodesFree     uint64                 `protobuf:"varint,5,opt,name=inodes_free,json=inodesFree,proto3" json:"inodes_free,omitempty"`
	Inodes         uint64                 `protobuf:"varint,6,opt,name=inodes,proto3" json:"inodes,omitempty"`
	InodesUsed     uint64                 `protobuf:"varint,7,opt,name=inodes_used,json=inodesUsed,proto3" json:"inodes_used,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FsStats) Reset() {
	*x = FsStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStats) ProtoMessage() {}

func (x *FsStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStats.ProtoReflect.Descriptor instead.
func (*FsStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{19}
}

func (x *FsStats) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *FsStats) GetAvailableBytes() uint64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *FsStats) GetCapacityBytes() uint64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *FsStats) GetUsedBytes() uint64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

func (x *FsStats) GetInodesFree() uint64 {
	if x != nil {
		return x.InodesFree
	}
	return 0
}

func (x *FsStats) GetInodes() uint64 {
	if x != nil {
		return x.Inodes
	}
	return 0
}

func (x *FsStats) GetInodesUsed() uint64 {
	if x != nil {
		return x.InodesUsed
	}
	return 0
}

type RuntimeStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeSeconds   int64                  `protobuf:"varint,1,opt,name=time_seconds,json=timeSeconds,proto3" json:"time_seconds,omitempty"`
	ImageFs       *FsStats               `protobuf:"bytes,2,opt,name=image_fs,json=imageFs,proto3" json:"image_fs,omitempty"`
	ContainerFs   *FsStats               `protobuf:"bytes,3,opt,name=container_fs,json=containerFs,proto3" json:"container_fs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeStats) Reset() {
	*x = RuntimeStats{}
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeStats) ProtoMessage() {}

func (x *RuntimeStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_kube_kube_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeStats.ProtoReflect.Descriptor instead.
func (*RuntimeStats) Descriptor() ([]byte, []int) {
	return file_api_v1_kube_kube_api_proto_rawDescGZIP(), []int{20}
}

func (x *RuntimeStats) GetTimeSeconds() int64 {
	if x != nil {
		return x.TimeSeconds
	}
	return 0
}

func (x *RuntimeStats) GetImageFs() *FsStats {
	if x != nil {
		return x.ImageFs
	}
	return nil
}

func (x *RuntimeStats) GetContainerFs() *FsStats {
	if x != nil {
		return x.ContainerFs
	}
	return nil
}

var File_api_v1_kube_kube_api_proto protoreflect.FileDescriptor

const file_api_v1_kube_kube_api_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/v1/kube/kube_api.proto\x12\akube.v1\"\x17\n" +
	"\x15GetClusterInfoRequest\"\xaf\x01\n" +
	"\x16GetClusterInfoResponse\x12\x1b\n" +
	"\tpods_cidr\x18\x01 \x03(\tR\bpodsCidr\x12!\n" +
	"\fservice_cidr\x18\x02 \x03(\tR\vserviceCidr\x12\x1b\n" +
	"\tnode_cidr\x18\x04 \x03(\tR\bnodeCidr\x12\x19\n" +
	"\bvpc_cidr\x18\x05 \x03(\tR\avpcCidr\x12\x1d\n" +
	"\n" +
	"other_cidr\x18\x03 \x03(\tR\totherCidr\"\"\n" +
	"\x10GetIPInfoRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\"8\n" +
	"\x11GetIPInfoResponse\x12#\n" +
	"\x04info\x18\x01 \x01(\v2\x0f.kube.v1.IPInfoR\x04info\"%\n" +
	"\x11GetIPsInfoRequest\x12\x10\n" +
	"\x03ips\x18\x01 \x03(\fR\x03ips\"9\n" +
	"\x12GetIPsInfoResponse\x12#\n" +
	"\x04list\x18\x01 \x03(\v2\x0f.kube.v1.IPInfoR\x04list\"\xc3\x02\n" +
	"\x06IPInfo\x12\x17\n" +
	"\apod_uid\x18\x01 \x01(\tR\x06podUid\x12\x19\n" +
	"\bpod_name\x18\x03 \x01(\tR\apodName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12#\n" +
	"\rworkload_name\x18\x04 \x01(\tR\fworkloadName\x12#\n" +
	"\rworkload_kind\x18\x05 \x01(\tR\fworkloadKind\x12!\n" +
	"\fworkload_uid\x18\x06 \x01(\tR\vworkloadUid\x12\x12\n" +
	"\x04zone\x18\a \x01(\tR\x04zone\x12\x16\n" +
	"\x06region\x18\n" +
	" \x01(\tR\x06region\x12\x1b\n" +
	"\tnode_name\x18\b \x01(\tR\bnodeName\x12!\n" +
	"\fcloud_domain\x18\v \x01(\tR\vcloudDomain\x12\x0e\n" +
	"\x02ip\x18\t \x01(\fR\x02ip\"!\n" +
	"\rGetPodRequest\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\tR\x03uid\"0\n" +
	"\x0eGetPodResponse\x12\x1e\n" +
	"\x03pod\x18\x01 \x01(\v2\f.kube.v1.PodR\x03pod\"\xd2\x01\n" +
	"\x03Pod\x12!\n" +
	"\fworkload_uid\x18\x01 \x01(\tR\vworkloadUid\x12#\n" +
	"\rworkload_name\x18\x02 \x01(\tR\fworkloadName\x12:\n" +
	"\rworkload_kind\x18\x03 \x01(\x0e2\x15.kube.v1.WorkloadKindR\fworkloadKind\x12\x12\n" +
	"\x04zone\x18\x04 \x01(\tR\x04zone\x12\x16\n" +
	"\x06region\x18\x06 \x01(\tR\x06region\x12\x1b\n" +
	"\tnode_name\x18\x05 \x01(\tR\bnodeName\"$\n" +
	"\x0eGetNodeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"4\n" +
	"\x0fGetNodeResponse\x12!\n" +
	"\x04node\x18\x01 \x01(\v2\r.kube.v1.NodeR\x04node\"\x88\x01\n" +
	"\x04Node\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x121\n" +
	"\x06labels\x18\x02 \x03(\v2\x19.kube.v1.Node.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"9\n" +
	"\x1aGetNodeStatsSummaryRequest\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\"E\n" +
	"\x1bGetNodeStatsSummaryResponse\x12&\n" +
	"\x04node\x18\x01 \x01(\v2\x12.kube.v1.NodeStatsR\x04node\"\xad\x02\n" +
	"\tNodeStats\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12,\n" +
	"\x12start_time_seconds\x18\x02 \x01(\x03R\x10startTimeSeconds\x12#\n" +
	"\x03cpu\x18\x03 \x01(\v2\x11.kube.v1.CPUStatsR\x03cpu\x12,\n" +
	"\x06memory\x18\x04 \x01(\v2\x14.kube.v1.MemoryStatsR\x06memory\x12/\n" +
	"\anetwork\x18\x05 \x01(\v2\x15.kube.v1.NetworkStatsR\anetwork\x12 \n" +
	"\x02fs\x18\x06 \x01(\v2\x10.kube.v1.FsStatsR\x02fs\x12/\n" +
	"\aruntime\x18\a \x01(\v2\x15.kube.v1.RuntimeStatsR\aruntime\"\x8c\x01\n" +
	"\bCPUStats\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12'\n" +
	"\x0fusage_nanocores\x18\x02 \x01(\x04R\x0eusageNanocores\x124\n" +
	"\x16usage_core_nanoseconds\x18\x03 \x01(\x04R\x14usageCoreNanoseconds\"\x90\x02\n" +
	"\vMemoryStats\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\x12\x1f\n" +
	"\vusage_bytes\x18\x03 \x01(\x04R\n" +
	"usageBytes\x12*\n" +
	"\x11working_set_bytes\x18\x04 \x01(\x04R\x0fworkingSetBytes\x12\x1b\n" +
	"\trss_bytes\x18\x05 \x01(\x04R\brssBytes\x12\x1f\n" +
	"\vpage_faults\x18\x06 \x01(\x04R\n" +
	"pageFaults\x12*\n" +
	"\x11major_page_faults\x18\a \x01(\x04R\x0fmajorPageFaults\"\xa1\x01\n" +
	"\fNetworkStats\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x1b\n" +
	"\trx_errors\x18\x03 \x01(\x04R\brxErrors\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\x12\x1b\n" +
	"\ttx_errors\x18\x05 \x01(\x04R\btxErrors\"\xf5\x01\n" +
	"\aFsStats\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12'\n" +
	"\x0favailable_bytes\x18\x02 \x01(\x04R\x0eavailableBytes\x12%\n" +
	"\x0ecapacity_bytes\x18\x03 \x01(\x04R\rcapacityBytes\x12\x1d\n" +
	"\n" +
	"used_bytes\x18\x04 \x01(\x04R\tusedBytes\x12\x1f\n" +
	"\vinodes_free\x18\x05 \x01(\x04R\n" +
	"inodesFree\x12\x16\n" +
	"\x06inodes\x18\x06 \x01(\x04R\x06inodes\x12\x1f\n" +
	"\vinodes_used\x18\a \x01(\x04R\n" +
	"inodesUsed\"\x93\x01\n" +
	"\fRuntimeStats\x12!\n" +
	"\ftime_seconds\x18\x01 \x01(\x03R\vtimeSeconds\x12+\n" +
	"\bimage_fs\x18\x02 \x01(\v2\x10.kube.v1.FsStatsR\aimageFs\x123\n" +
	"\fcontainer_fs\x18\x03 \x01(\v2\x10.kube.v1.FsStatsR\vcontainerFs*\xed\x01\n" +
	"\fWorkloadKind\x12\x19\n" +
	"\x15WORKLOAD_KIND_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18WORKLOAD_KIND_DEPLOYMENT\x10\x01\x12\x1d\n" +
	"\x19WORKLOAD_KIND_REPLICA_SET\x10\x02\x12\x1e\n" +
	"\x1aWORKLOAD_KIND_STATEFUL_SET\x10\x03\x12\x1c\n" +
	"\x18WORKLOAD_KIND_DAEMON_SET\x10\x04\x12\x15\n" +
	"\x11WORKLOAD_KIND_JOB\x10\x05\x12\x19\n" +
	"\x15WORKLOAD_KIND_CRONJOB\x10\x06\x12\x15\n" +
	"\x11WORKLOAD_KIND_POD\x10\a2\xc2\x03\n" +
	"\aKubeAPI\x12Q\n" +
	"\x0eGetClusterInfo\x12\x1e.kube.v1.GetClusterInfoRequest\x1a\x1f.kube.v1.GetClusterInfoResponse\x12B\n" +
	"\tGetIPInfo\x12\x19.kube.v1.GetIPInfoRequest\x1a\x1a.kube.v1.GetIPInfoResponse\x12E\n" +
	"\n" +
	"GetIPsInfo\x12\x1a.kube.v1.GetIPsInfoRequest\x1a\x1b.kube.v1.GetIPsInfoResponse\x129\n" +
	"\x06GetPod\x12\x16.kube.v1.GetPodRequest\x1a\x17.kube.v1.GetPodResponse\x12<\n" +
	"\aGetNode\x12\x17.kube.v1.GetNodeRequest\x1a\x18.kube.v1.GetNodeResponse\x12`\n" +
	"\x13GetNodeStatsSummary\x12#.kube.v1.GetNodeStatsSummaryRequest\x1a$.kube.v1.GetNodeStatsSummaryResponseB&Z$github.com/castai/kvisor/api/kube/v1b\x06proto3"

var (
	file_api_v1_kube_kube_api_proto_rawDescOnce sync.Once
	file_api_v1_kube_kube_api_proto_rawDescData []byte
)

func file_api_v1_kube_kube_api_proto_rawDescGZIP() []byte {
	file_api_v1_kube_kube_api_proto_rawDescOnce.Do(func() {
		file_api_v1_kube_kube_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_kube_kube_api_proto_rawDesc), len(file_api_v1_kube_kube_api_proto_rawDesc)))
	})
	return file_api_v1_kube_kube_api_proto_rawDescData
}

var file_api_v1_kube_kube_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_v1_kube_kube_api_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_v1_kube_kube_api_proto_goTypes = []any{
	(WorkloadKind)(0),                   // 0: kube.v1.WorkloadKind
	(*GetClusterInfoRequest)(nil),       // 1: kube.v1.GetClusterInfoRequest
	(*GetClusterInfoResponse)(nil),      // 2: kube.v1.GetClusterInfoResponse
	(*GetIPInfoRequest)(nil),            // 3: kube.v1.GetIPInfoRequest
	(*GetIPInfoResponse)(nil),           // 4: kube.v1.GetIPInfoResponse
	(*GetIPsInfoRequest)(nil),           // 5: kube.v1.GetIPsInfoRequest
	(*GetIPsInfoResponse)(nil),          // 6: kube.v1.GetIPsInfoResponse
	(*IPInfo)(nil),                      // 7: kube.v1.IPInfo
	(*GetPodRequest)(nil),               // 8: kube.v1.GetPodRequest
	(*GetPodResponse)(nil),              // 9: kube.v1.GetPodResponse
	(*Pod)(nil),                         // 10: kube.v1.Pod
	(*GetNodeRequest)(nil),              // 11: kube.v1.GetNodeRequest
	(*GetNodeResponse)(nil),             // 12: kube.v1.GetNodeResponse
	(*Node)(nil),                        // 13: kube.v1.Node
	(*GetNodeStatsSummaryRequest)(nil),  // 14: kube.v1.GetNodeStatsSummaryRequest
	(*GetNodeStatsSummaryResponse)(nil), // 15: kube.v1.GetNodeStatsSummaryResponse
	(*NodeStats)(nil),                   // 16: kube.v1.NodeStats
	(*CPUStats)(nil),                    // 17: kube.v1.CPUStats
	(*MemoryStats)(nil),                 // 18: kube.v1.MemoryStats
	(*NetworkStats)(nil),                // 19: kube.v1.NetworkStats
	(*FsStats)(nil),                     // 20: kube.v1.FsStats
	(*RuntimeStats)(nil),                // 21: kube.v1.RuntimeStats
	nil,                                 // 22: kube.v1.Node.LabelsEntry
}
var file_api_v1_kube_kube_api_proto_depIdxs = []int32{
	7,  // 0: kube.v1.GetIPInfoResponse.info:type_name -> kube.v1.IPInfo
	7,  // 1: kube.v1.GetIPsInfoResponse.list:type_name -> kube.v1.IPInfo
	10, // 2: kube.v1.GetPodResponse.pod:type_name -> kube.v1.Pod
	0,  // 3: kube.v1.Pod.workload_kind:type_name -> kube.v1.WorkloadKind
	13, // 4: kube.v1.GetNodeResponse.node:type_name -> kube.v1.Node
	22, // 5: kube.v1.Node.labels:type_name -> kube.v1.Node.LabelsEntry
	16, // 6: kube.v1.GetNodeStatsSummaryResponse.node:type_name -> kube.v1.NodeStats
	17, // 7: kube.v1.NodeStats.cpu:type_name -> kube.v1.CPUStats
	18, // 8: kube.v1.NodeStats.memory:type_name -> kube.v1.MemoryStats
	19, // 9: kube.v1.NodeStats.network:type_name -> kube.v1.NetworkStats
	20, // 10: kube.v1.NodeStats.fs:type_name -> kube.v1.FsStats
	21, // 11: kube.v1.NodeStats.runtime:type_name -> kube.v1.RuntimeStats
	20, // 12: kube.v1.RuntimeStats.image_fs:type_name -> kube.v1.FsStats
	20, // 13: kube.v1.RuntimeStats.container_fs:type_name -> kube.v1.FsStats
	1,  // 14: kube.v1.KubeAPI.GetClusterInfo:input_type -> kube.v1.GetClusterInfoRequest
	3,  // 15: kube.v1.KubeAPI.GetIPInfo:input_type -> kube.v1.GetIPInfoRequest
	5,  // 16: kube.v1.KubeAPI.GetIPsInfo:input_type -> kube.v1.GetIPsInfoRequest
	8,  // 17: kube.v1.KubeAPI.GetPod:input_type -> kube.v1.GetPodRequest
	11, // 18: kube.v1.KubeAPI.GetNode:input_type -> kube.v1.GetNodeRequest
	14, // 19: kube.v1.KubeAPI.GetNodeStatsSummary:input_type -> kube.v1.GetNodeStatsSummaryRequest
	2,  // 20: kube.v1.KubeAPI.GetClusterInfo:output_type -> kube.v1.GetClusterInfoResponse
	4,  // 21: kube.v1.KubeAPI.GetIPInfo:output_type -> kube.v1.GetIPInfoResponse
	6,  // 22: kube.v1.KubeAPI.GetIPsInfo:output_type -> kube.v1.GetIPsInfoResponse
	9,  // 23: kube.v1.KubeAPI.GetPod:output_type -> kube.v1.GetPodResponse
	12, // 24: kube.v1.KubeAPI.GetNode:output_type -> kube.v1.GetNodeResponse
	15, // 25: kube.v1.KubeAPI.GetNodeStatsSummary:output_type -> kube.v1.GetNodeStatsSummaryResponse
	20, // [20:26] is the sub-list for method output_type
	14, // [14:20] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_v1_kube_kube_api_proto_init() }
func file_api_v1_kube_kube_api_proto_init() {
	if File_api_v1_kube_kube_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_kube_kube_api_proto_rawDesc), len(file_api_v1_kube_kube_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_kube_kube_api_proto_goTypes,
		DependencyIndexes: file_api_v1_kube_kube_api_proto_depIdxs,
		EnumInfos:         file_api_v1_kube_kube_api_proto_enumTypes,
		MessageInfos:      file_api_v1_kube_kube_api_proto_msgTypes,
	}.Build()
	File_api_v1_kube_kube_api_proto = out.File
	file_api_v1_kube_kube_api_proto_goTypes = nil
	file_api_v1_kube_kube_api_proto_depIdxs = nil
}
