// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.0
// source: api/v1/kube/kube_api.proto

package v1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KubeAPI_GetClusterInfo_FullMethodName      = "/kube.v1.KubeAPI/GetClusterInfo"
	KubeAPI_GetIPInfo_FullMethodName           = "/kube.v1.KubeAPI/GetIPInfo"
	KubeAPI_GetIPsInfo_FullMethodName          = "/kube.v1.KubeAPI/GetIPsInfo"
	KubeAPI_GetPod_FullMethodName              = "/kube.v1.KubeAPI/GetPod"
	KubeAPI_GetNode_FullMethodName             = "/kube.v1.KubeAPI/GetNode"
	KubeAPI_GetNodeStatsSummary_FullMethodName = "/kube.v1.KubeAPI/GetNodeStatsSummary"
	KubeAPI_GetPodVolumes_FullMethodName       = "/kube.v1.KubeAPI/GetPodVolumes"
)

// KubeAPIClient is the client API for KubeAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KubeAPIClient interface {
	GetClusterInfo(ctx context.Context, in *GetClusterInfoRequest, opts ...grpc.CallOption) (*GetClusterInfoResponse, error)
	// GetIPInfo is deprecated, use GetIPsInfo.
	GetIPInfo(ctx context.Context, in *GetIPInfoRequest, opts ...grpc.CallOption) (*GetIPInfoResponse, error)
	GetIPsInfo(ctx context.Context, in *GetIPsInfoRequest, opts ...grpc.CallOption) (*GetIPsInfoResponse, error)
	GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*GetPodResponse, error)
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	GetNodeStatsSummary(ctx context.Context, in *GetNodeStatsSummaryRequest, opts ...grpc.CallOption) (*GetNodeStatsSummaryResponse, error)
	GetPodVolumes(ctx context.Context, in *GetPodVolumesRequest, opts ...grpc.CallOption) (*GetPodVolumesResponse, error)
}

type kubeAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewKubeAPIClient(cc grpc.ClientConnInterface) KubeAPIClient {
	return &kubeAPIClient{cc}
}

func (c *kubeAPIClient) GetClusterInfo(ctx context.Context, in *GetClusterInfoRequest, opts ...grpc.CallOption) (*GetClusterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterInfoResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetClusterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetIPInfo(ctx context.Context, in *GetIPInfoRequest, opts ...grpc.CallOption) (*GetIPInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPInfoResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetIPInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetIPsInfo(ctx context.Context, in *GetIPsInfoRequest, opts ...grpc.CallOption) (*GetIPsInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIPsInfoResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetIPsInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*GetPodResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetPod_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetNodeStatsSummary(ctx context.Context, in *GetNodeStatsSummaryRequest, opts ...grpc.CallOption) (*GetNodeStatsSummaryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeStatsSummaryResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetNodeStatsSummary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kubeAPIClient) GetPodVolumes(ctx context.Context, in *GetPodVolumesRequest, opts ...grpc.CallOption) (*GetPodVolumesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPodVolumesResponse)
	err := c.cc.Invoke(ctx, KubeAPI_GetPodVolumes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KubeAPIServer is the server API for KubeAPI service.
// All implementations should embed UnimplementedKubeAPIServer
// for forward compatibility.
type KubeAPIServer interface {
	GetClusterInfo(context.Context, *GetClusterInfoRequest) (*GetClusterInfoResponse, error)
	// GetIPInfo is deprecated, use GetIPsInfo.
	GetIPInfo(context.Context, *GetIPInfoRequest) (*GetIPInfoResponse, error)
	GetIPsInfo(context.Context, *GetIPsInfoRequest) (*GetIPsInfoResponse, error)
	GetPod(context.Context, *GetPodRequest) (*GetPodResponse, error)
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	GetNodeStatsSummary(context.Context, *GetNodeStatsSummaryRequest) (*GetNodeStatsSummaryResponse, error)
	GetPodVolumes(context.Context, *GetPodVolumesRequest) (*GetPodVolumesResponse, error)
}

// UnimplementedKubeAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKubeAPIServer struct{}

func (UnimplementedKubeAPIServer) GetClusterInfo(context.Context, *GetClusterInfoRequest) (*GetClusterInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterInfo not implemented")
}
func (UnimplementedKubeAPIServer) GetIPInfo(context.Context, *GetIPInfoRequest) (*GetIPInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPInfo not implemented")
}
func (UnimplementedKubeAPIServer) GetIPsInfo(context.Context, *GetIPsInfoRequest) (*GetIPsInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIPsInfo not implemented")
}
func (UnimplementedKubeAPIServer) GetPod(context.Context, *GetPodRequest) (*GetPodResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPod not implemented")
}
func (UnimplementedKubeAPIServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedKubeAPIServer) GetNodeStatsSummary(context.Context, *GetNodeStatsSummaryRequest) (*GetNodeStatsSummaryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStatsSummary not implemented")
}
func (UnimplementedKubeAPIServer) GetPodVolumes(context.Context, *GetPodVolumesRequest) (*GetPodVolumesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPodVolumes not implemented")
}
func (UnimplementedKubeAPIServer) testEmbeddedByValue() {}

// UnsafeKubeAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KubeAPIServer will
// result in compilation errors.
type UnsafeKubeAPIServer interface {
	mustEmbedUnimplementedKubeAPIServer()
}

func RegisterKubeAPIServer(s grpc.ServiceRegistrar, srv KubeAPIServer) {
	// If the following call panics, it indicates UnimplementedKubeAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KubeAPI_ServiceDesc, srv)
}

func _KubeAPI_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetClusterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetClusterInfo(ctx, req.(*GetClusterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetIPInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetIPInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetIPInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetIPInfo(ctx, req.(*GetIPInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetIPsInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIPsInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetIPsInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetIPsInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetIPsInfo(ctx, req.(*GetIPsInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetPod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetPod(ctx, req.(*GetPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetNodeStatsSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeStatsSummaryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetNodeStatsSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetNodeStatsSummary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetNodeStatsSummary(ctx, req.(*GetNodeStatsSummaryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KubeAPI_GetPodVolumes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodVolumesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KubeAPIServer).GetPodVolumes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KubeAPI_GetPodVolumes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KubeAPIServer).GetPodVolumes(ctx, req.(*GetPodVolumesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KubeAPI_ServiceDesc is the grpc.ServiceDesc for KubeAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KubeAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kube.v1.KubeAPI",
	HandlerType: (*KubeAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClusterInfo",
			Handler:    _KubeAPI_GetClusterInfo_Handler,
		},
		{
			MethodName: "GetIPInfo",
			Handler:    _KubeAPI_GetIPInfo_Handler,
		},
		{
			MethodName: "GetIPsInfo",
			Handler:    _KubeAPI_GetIPsInfo_Handler,
		},
		{
			MethodName: "GetPod",
			Handler:    _KubeAPI_GetPod_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _KubeAPI_GetNode_Handler,
		},
		{
			MethodName: "GetNodeStatsSummary",
			Handler:    _KubeAPI_GetNodeStatsSummary_Handler,
		},
		{
			MethodName: "GetPodVolumes",
			Handler:    _KubeAPI_GetPodVolumes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/kube/kube_api.proto",
}
