linters:
  disable:
    - wrapcheck
    - err113
    - contextcheck
    - exhaustive
    - protogetter
  presets:
    - bugs
    - error
    - unused

run:
  tests: false

issues:
  exclude-dirs:
    - .github
    - charts
    - examples
    - ui
    - tools
    - dist
    - bin
    - api
    - research
    - tools
    - cmd/linter/kubebench
