linters:
  enable:
    - gosimple
  disable:
    - scopelint
    - deadcode
    - maligned
    - structcheck
    - varcheck
    - prealloc
    - contextcheck
    - protogetter
  presets:
    - bugs
    - performance
    - unused

run:
  skip-dirs:
    - .github
    - charts
    - examples
