FROM alpine:3.23.4@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11

RUN apk update && apk add curl bash
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && VERIFY_CHECKSUM=false ./get_helm.sh

WORKDIR /source
COPY ./bin/kvisor-e2e /usr/local/bin/kvisor-e2e
COPY ./charts ./charts
ARG image_tag
ENV env_image_tag $image_tag

CMD ["sh", "-c", "/usr/local/bin/kvisor-e2e --image-tag=${env_image_tag}"]
