FROM cgr.dev/chainguard/static:latest@sha256:8d1a96321dca0e8e7848b7db2d431191f15e7e302faa1428100bbab351d42c7a

ARG TARGETARCH
COPY ./bin/kvisor-controller-$TARGETARCH /usr/local/bin/kvisor-controller

ENTRYPOINT ["/usr/local/bin/kvisor-controller"]
