FROM alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d

RUN apk update && apk add curl bash
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && VERIFY_CHECKSUM=false ./get_helm.sh

WORKDIR /source
COPY ./bin/kvisor-e2e /usr/local/bin/kvisor-e2e
COPY ./charts ./charts
ARG image_tag
ENV env_image_tag $image_tag

CMD ["sh", "-c", "/usr/local/bin/kvisor-e2e --image-tag=${env_image_tag}"]
