FROM alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375

# Needed for kube-bench.
RUN apk --no-cache add procps

COPY bin/kvisor-linter /usr/local/bin/kvisor-linter
COPY bin/kvisor-image-scanner /usr/local/bin/kvisor-image-scanner
COPY cmd/linter/kubebench/kubebench-rules /etc/kubebench-rules
