version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:26.3.9.8-alpine@sha256:b98554227ed543d21d2cd632df77fb2060454a2caeab47929fa6118c9f8bbe2f
    restart: always
    environment:
      - CLICKHOUSE_USER=storage
      - CLICKHOUSE_PASSWORD=storage
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse:/var/lib/clickhouse/

volumes:
  db:
    driver: local
  clickhouse:
    driver: local
