FROM cgr.dev/chainguard/static:latest@sha256:5ff428f8a48241b93a4174dbbc135a4ffb2381a9e10bdbbc5b9db145645886d5

# the agent needs to run as root, there is no way around this
USER 0

ARG TARGETARCH
COPY bin/kvisor-agent-$TARGETARCH /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
