FROM alpine:3.21.2@sha256:56fa17d2a7e7f168a043a2712e63aed1f8543aeafdcee47c58dcffe38ed51099

# Needed for kube-bench.
RUN apk --no-cache add procps

ARG TARGETARCH
COPY bin/kvisor-linter-$TARGETARCH /usr/local/bin/kvisor-linter
COPY bin/kvisor-image-scanner-$TARGETARCH /usr/local/bin/kvisor-image-scanner
COPY cmd/linter/kubebench/kubebench-rules /etc/kubebench-rules
