FROM cgr.dev/chainguard/static:latest@sha256:1ff7590cbc50eaaa917c34b092de0720d307f67d6d795e4f749a0b80a2e95a2c

# the agent needs to run as root, there is no way around this
USER 0

ARG TARGETARCH
COPY bin/kvisor-agent-$TARGETARCH /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
