FROM alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

# Needed for kube-bench.
RUN apk --no-cache add procps

COPY bin/kvisor-node-collector /usr/local/bin/kvisor-node-collector
