FROM alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

# the agent needs to run as root, there is no way around this
USER 0

COPY bin/kvisor-agent /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
