FROM alpine:3.19.1

# Needed for kube-bench.
RUN apk --no-cache add procps

COPY bin/kvisor-linter /usr/local/bin/kvisor-linter
COPY bin/kvisor-image-scanner /usr/local/bin/kvisor-image-scanner
COPY cmd/linter/kubebench/kubebench-rules /etc/kubebench-rules
