FROM alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

ARG TARGETARCH
COPY ./bin/kvisor-node-collector-$TARGETARCH /app/kvisor-node-collector

ENTRYPOINT ["/app/kvisor-node-collector"]
