FROM gcr.io/distroless/static-debian11 as base

FROM base as base-with-shell
# For tilt environment a shell is required for docker_build_with_restart.
WORKDIR /
COPY --from=busybox:uclibc /bin/sh /bin/sh
COPY --from=busybox:uclibc /bin/busybox /busybox
SHELL ["/bin/sh", "-c"]
RUN /busybox --install

FROM base-with-shell

COPY ./bin/castai-kvisor /usr/local/bin/castai-kvisor
CMD ["/usr/local/bin/castai-kvisor"]

