FROM alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

# the agent needs to run as root, there is no way around this
USER 0

COPY bin/kvisor-agent /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
