FROM alpine:3.23.0@sha256:51183f2cfa6320055da30872f211093f9ff1d3cf06f39a0bdb212314c5dc7375

# the agent needs to run as root, there is no way around this
USER 0

COPY bin/kvisor-agent /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
