FROM alpine:3.19.1@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

# Needed for kube-bench.
RUN apk --no-cache add procps

COPY bin/kvisor-linter /usr/local/bin/kvisor-linter
COPY bin/kvisor-image-scanner /usr/local/bin/kvisor-image-scanner
COPY cmd/linter/kubebench/kubebench-rules /etc/kubebench-rules
