FROM alpine:3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c

RUN apk update && apk add curl bash
RUN curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 && chmod 700 get_helm.sh && VERIFY_CHECKSUM=false ./get_helm.sh

WORKDIR /source
COPY ./bin/kvisor-e2e /usr/local/bin/kvisor-e2e
COPY ./charts ./charts
ARG image_tag
ENV env_image_tag $image_tag

CMD ["sh", "-c", "/usr/local/bin/kvisor-e2e --image-tag=${env_image_tag}"]
