FROM cgr.dev/chainguard/static:latest@sha256:a301031ffd4ed67f35ca7fa6cf3dad9937b5fa47d7493955a18d9b4ca5412d1a

# the agent needs to run as root, there is no way around this
USER 0

ARG TARGETARCH
COPY bin/kvisor-agent-$TARGETARCH /usr/local/bin/kvisor-agent

ENTRYPOINT ["/usr/local/bin/kvisor-agent"]
