FROM alpine:3.20.3@sha256:1e42bbe2508154c9126d48c2b8a75420c3544343bf86fd041fb7527e017a4b4a

# Needed for kube-bench.
RUN apk --no-cache add procps

ARG TARGETARCH
COPY bin/kvisor-linter-$TARGETARCH /usr/local/bin/kvisor-linter
COPY bin/kvisor-image-scanner-$TARGETARCH /usr/local/bin/kvisor-image-scanner
COPY cmd/linter/kubebench/kubebench-rules /etc/kubebench-rules
