version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.10.2.65-alpine@sha256:81ce9121febca7b12c75cf1aae448ccfaef0f68da25802ad805e81f8af610de9
    restart: always
    environment:
      - CLICKHOUSE_USER=storage
      - CLICKHOUSE_PASSWORD=storage
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse:/var/lib/clickhouse/

volumes:
  db:
    driver: local
  clickhouse:
    driver: local
