version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.3.22-alpine@sha256:ce7c85882c70fdce83ac5220a5b12da60f18745352a1e2a42097be2bda19497d
    restart: always
    environment:
      - CLICKHOUSE_USER=storage
      - CLICKHOUSE_PASSWORD=storage
      - CLICKHOUSE_DB=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse:/var/lib/clickhouse/

volumes:
  db:
    driver: local
  clickhouse:
    driver: local
