FROM cgr.dev/chainguard/static:latest@sha256:d07036a3beff43183f49bce5b2a0bd945f2ffe6e76f734ebd040059a40d371bc

ARG TARGETARCH
COPY ./bin/kvisor-controller-$TARGETARCH /usr/local/bin/kvisor-controller

ENTRYPOINT ["/usr/local/bin/kvisor-controller"]
