apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy

metadata:
  name: "exposed-ssh-port.policies.cast.ai"
  labels:
    cast.ai/policy: exposed-ssh-port
spec:
  failurePolicy: Fail

  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - pods
        - replicationcontrollers
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - deployments
        - daemonsets
        - statefulsets
        - replicasets
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - jobs
        - cronjobs
    - apiGroups:   ["apps.openshift.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - deploymentconfigs

  variables:
  - name: containers
    expression: "has(object.spec.template) ? object.spec.template.spec.containers : object.spec.containers"

  validations:
  - expression: "variables.containers.filter(c, c.ports.filter(p, p.containerPort == 22).size() > 0).size() == 0"
    message: "container exposes SSH port"
