apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "non-readonly-rootfs.policies.cast.ai"
  labels:
    cast.ai/policy: non-readonly-rootfs
spec:
  failurePolicy: Fail

  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - pods
        - replicationcontrollers
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - deployments
        - daemonsets
        - statefulsets
        - replicasets
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - jobs
        - cronjobs
    - apiGroups:   ["apps.openshift.io"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:
        - deploymentconfigs

  variables:
  - name: containers
    expression: "object.spec.template.spec.containers"

  validations:
  - expression: "variables.containers.filter(c, c.securityContext && c.securityContext.readOnlyRootFilesystem == false).size() == 0"
    message: "container has a non-readonly root filesystem"