apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: None
  resources:
  - group: "coordination.k8s.io"
    resources: ["leases"]
- level: Metadata
  resources:
  - group: ""
    resources: ["pods"]
