apiVersion: v1
kind: Config
preferences: {}
clusters:
- name: local-webhook
  cluster:
    server: http://192.168.1.128:8080
users:
- name: noauth
  user:
    username: noauth
    password: noauth
contexts:
- name: local-context
  context:
    cluster: local-webhook
    user: noauth
current-context: local-context
