apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 178df4de9d42f5e642fbe49e62950ed68259d929b68b987cced3b11bb215891f
    cni.projectcalico.org/podIP: 10.48.1.26/32
    cni.projectcalico.org/podIPs: 10.48.1.26/32
  creationTimestamp: "2023-12-26T09:37:34Z"
  generateName: oom-test-b55b45f99-
  labels:
    app: oom-test
    pod-template-hash: b55b45f99
  name: oom-test-b55b45f99-2dg27
  namespace: demo
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: oom-test-b55b45f99
    uid: 2aeb4503-124a-47e3-a985-853cb64bba7e
  resourceVersion: "92769744"
  uid: 6142a1d5-3982-43b5-8a78-a6a1866047d4
spec:
  containers:
  - args:
    - -mem-total2
    - 1Gi
    - -mem-alloc-size
    - 100Mi
    image: vish/stress
    imagePullPolicy: Always
    name: stress
    resources:
      limits:
        memory: 10Mi
      requests:
        memory: 10Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7n5dn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-demo-pool-1-96567561-ukhh
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-7n5dn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-12-26T09:37:34Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-12-26T09:37:34Z"
    message: 'containers with unready status: [stress]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-12-26T09:37:34Z"
    message: 'containers with unready status: [stress]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-12-26T09:37:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://b821a5cc01a6c177c087a11b72bb455f0412ca5a849b48887c5b72861b667a4c
    image: docker.io/vish/stress:latest
    imageID: docker.io/vish/stress@sha256:b6456a3df6db5e063e1783153627947484a3db387be99e49708c70a9a15e7177
    lastState:
      terminated:
        containerID: containerd://8a8394dd3bb44f4f727d38f98088b27b18787fa129e597a6c309382a927030db
        exitCode: 2
        finishedAt: "2023-12-26T09:37:35Z"
        reason: Error
        startedAt: "2023-12-26T09:37:35Z"
    name: stress
    ready: false
    restartCount: 2
    started: false
    state:
      terminated:
        containerID: containerd://b821a5cc01a6c177c087a11b72bb455f0412ca5a849b48887c5b72861b667a4c
        exitCode: 2
        finishedAt: "2023-12-26T09:37:53Z"
        reason: Error
        startedAt: "2023-12-26T09:37:53Z"
  hostIP: 10.128.0.6
  phase: Running
  podIP: 10.48.1.26
  podIPs:
  - ip: 10.48.1.26
  qosClass: Burstable
  startTime: "2023-12-26T09:37:34Z"
