apiVersion: v2
name: castai-kvisor
description: CAST AI security and observability.
type: application
version: 1.0.153
appVersion: "v1.55.23"

dependencies:
  - name: reliability-metrics-ch-exporter
    version: "0.3.17"
    repository: "https://castai.github.io/helm-charts"
    condition: reliabilityMetrics.enabled
    alias: reliabilityMetrics
