---
apiVersion: v1
kind: Service
metadata:
  name: echo-a-ipv4
  labels:
    name: echo-a
spec:
  type: ClusterIP
  ipFamilies:
    - IPv4
  selector:
    name: echo-a
  ports:
    - name: http
      port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-a-ipv6
  labels:
    name: echo-a
spec:
  type: ClusterIP
  ipFamilies:
    - IPv6
  selector:
    name: echo-a
  ports:
    - name: http
      port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-a
  labels:
    name: echo-a
spec:
  replicas: 2
  selector:
    matchLabels:
      name: echo-a
  template:
    metadata:
      annotations:
        cast.ai/e2e: e2e
      labels:
        name: echo-a
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 1
      containers:
        - name: echo-a-container
          env:
            - name: PORT
              value: "8080"
          ports:
            - containerPort: 8080
          image: quay.io/cilium/json-mock:v1.3.2@sha256:bc6c46c74efadb135bc996c2467cece6989302371ef4e3f068361460abaf39be
          imagePullPolicy: IfNotPresent
          readinessProbe:
            timeoutSeconds: 7
            exec:
              command:
                - curl
                - -sS
                - --fail
                - --connect-timeout
                - "5"
                - -o
                - /dev/null
                - localhost:8080
          livenessProbe:
            timeoutSeconds: 7
            exec:
              command:
                - curl
                - -sS
                - --fail
                - --connect-timeout
                - "5"
                - -o
                - /dev/null
                - localhost:8080
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-to-a
  labels:
    name: pod-to-a
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: pod-to-a
    spec:
      hostNetwork: false
      terminationGracePeriodSeconds: 1
      containers:
        - name: pod-to-a-container
          ports: []
          image: quay.io/cilium/alpine-curl:v1.5.0@sha256:7b286939730d8af1149ef88dba15739d8330bb83d7d9853a23e5ab4043e2d33c
          imagePullPolicy: IfNotPresent
          command:
            - /bin/ash
            - -c
            - |
              while true; do
                curl echo-a-ipv4:8080/public
                curl echo-a-ipv6:8080/public
                sleep 3
              done
          readinessProbe:
            timeoutSeconds: 7
            exec:
              command:
                - curl
                - -sS
                - --fail
                - --connect-timeout
                - "5"
                - -o
                - /dev/null
                - echo-a-ipv4:8080/public
          livenessProbe:
            timeoutSeconds: 7
            exec:
              command:
                - curl
                - -sS
                - --fail
                - --connect-timeout
                - "5"
                - -o
                - /dev/null
                - echo-a-ipv6:8080/public
  selector:
    matchLabels:
      name: pod-to-a
