apiVersion: apps/v1
kind: Deployment
metadata:
  name: e2e
  namespace: castai-kvisor-e2e
  labels:
    app.kubernetes.io/name: e2e
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: e2e
  replicas: 1
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: e2e
    spec:
      containers:
        - name: e2e
          image: "kvisor-e2e:local"
          ports:
            - name: http
              containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: e2e
  namespace: castai-kvisor-e2e
  labels:
    app.kubernetes.io/name: e2e
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: e2e
