kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: e2e
networking:
  ipFamily: dual
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".containerd]
      discard_unpacked_layers = false
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
      endpoint = ["https://mirror.gcr.io"]
