apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic-write-generator
  labels:
    app: magic-write-generator
spec:
  selector:
    matchLabels:
      app: magic-write-generator
  replicas: 1
  template:
    metadata:
      annotations:
        cast.ai/e2e: e2e
      labels:
        app: magic-write-generator
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: magic-write-generator
          image: ubuntu:rolling
          command:
            - /bin/sh
            - -c
            - |-
              sleep 2
              TEMP_ARCHIVE=$(mktemp --suffix .tar.gz)
              cd /tmp
              cp /bin/tar tar_executable
              chmod -x tar_executable
              tar czvf $TEMP_ARCHIVE tar_executable

              for i in $(seq 0 10000); do
                TEMP=$(mktemp -d)
                cd $TEMP
                tar xzf $TEMP_ARCHIVE
                chmod +x tar_executable
                ./tar_executable || true
                sleep 1
                echo $i $TEMP
                cd /tmp
                rm -rf $TEMP
              done
              sleep 2
