{
 "title": "Kvisor",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Controller", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"castai-kvisor-controller-(.*)\", image!=\"\", name!~\".*POD.*\", cpu=\"total\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"castai-kvisor-controller-(.*)\",name!~\".*POD.*\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total network usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"castai-kvisor-controller-(.*)\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{pod=~\"castai-kvisor-controller-(.*)\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Agent", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"castai-kvisor-agent-(.*)\", image!=\"\", name!~\".*POD.*\", cpu=\"total\"}[1m]))",
     "legendFormat": "Sum"
    },
    {
     "expr": "avg(rate(container_cpu_usage_seconds_total{pod=~\"castai-kvisor-agent-(.*)\", image!=\"\", name!~\".*POD.*\", cpu=\"total\", container!=\"pyroscope\"}[1m]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Total memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{pod=~\"castai-kvisor-agent-(.*)\",name!~\".*POD.*\", image!=\"\"})",
     "legendFormat": "Sum"
    },
    {
     "expr": "avg(container_memory_working_set_bytes{pod=~\"castai-kvisor-agent-(.*)\",name!~\".*POD.*\", image!=\"\"})",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Total network usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{pod=~\"castai-kvisor-agent-(.*)\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (rate(container_network_transmit_bytes_total{pod=~\"castai-kvisor-agent-(.*)\"}[1m]))",
     "legendFormat": "Transmit"
    }
   ]
  },
  { "title": "Agent EBPF stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Pulled events from kernel (rate)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_kernel_pulled_events_total{}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Pulled events from kernel (size)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_kernel_pulled_events_bytes_total{}[1m])) by (event_type)",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Exported data rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_send_total{}[1m])) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Export errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_send_errors_total{}[1m])) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Agent events rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_kernel_pulled_events_total{}[1m]))",
     "legendFormat": "Kernel pulled events"
    },
    {
     "expr": "sum(rate(kvisor_agent_skipped_events_total{}[1m]))",
     "legendFormat": "Skipped events rate"
    },
    {
     "expr": "sum(rate(kvisor_agent_kernel_lost_events_total{}[1m]))",
     "legendFormat": "Lost events"
    },
    {
     "expr": " sum(rate(kvisor_agent_exporter_send_total{}[1m]))",
     "legendFormat": "Exported events"
    }
   ]
  },
  {
   "title": "Export errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_send_errors_total{}[1m])) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter dropped queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_queue_dropped_total{}[1m])) by (exporter)",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "Netflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "title": "Netflows traffic (console namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, interval 1 minute) AS time, sum(tx_bytes) tx_total, sum(rx_bytes) rx_total from netflows \nwhere cluster_id='c92acdca-b949-4ca1-b916-442c175245ce' \nand namespace='console'\nand ( ts >= $__fromTime AND ts <= $__toTime ) \ngroup by time\norder by time;"
      }
     ]
    },
    {
     "title": "Container traffic (console namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"console\", image!=\"\"}[1m]))",
       "legendFormat": "tx_total"
      },
      {
       "expr": "sum(increase(container_network_receive_bytes_total{namespace=\"console\", image!=\"\"}[1m]))",
       "legendFormat": "rx_total"
      }
     ]
    },
    {
     "title": "Netflows traffic (console namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, interval 1 minute) AS time, pod_name, sum(tx_bytes) tx_total from netflows \nwhere cluster_id='c92acdca-b949-4ca1-b916-442c175245ce' \nand namespace='console' and pod_name like 'cluster-snapshots-%'\nand ( ts >= $__fromTime AND ts <= $__toTime ) \ngroup by time, pod_name\norder by time, pod_name"
      }
     ]
    },
    {
     "title": "Container traffic (console namespace)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(increase(container_network_transmit_bytes_total{namespace=\"console\", image!=\"\" ,pod=~\"cluster-snapshots-.*\"}[1m])) by (pod)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}