{
 "title": "Kvisord",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Kvisord metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"kvisord\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"kvisord\"}[2m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "KV storage ops rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(kvisord_kv_storage_ops_total{}[1m])) by (op_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inserted events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(kvisord_storage_inserted_events_total{}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "sum(rate(kvisord_storage_dropped_events_total{}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{namespace=\"kvisord\"}) by (persistentvolumeclaim)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Events by kind",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select count(*) total, kind from events\ngroup by kind\norder by total desc;"
    }
   ]
  },
  {
   "title": "Events total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "select count(*) from events;" }
   ]
  },
  { "title": "Kvisord agents metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Ebpf events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(tracee_ebpf_events_total{}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ebpf lost events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(tracee_ebpf_lostevents_total{}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exported events rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(kvisord_exported_events_total{}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Exported events bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(kvisord_events_bytes{}[2m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DNS events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 11, "w": 4, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from events where name='net_packet_dns'"
      }
     ]
    },
    {
     "title": "DNS requests",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 20, "x": 4, "y": 18 },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) m, count(*) total, container_name, namespace from events\nwhere $__timeFilter(ts) and name='net_packet_dns'\ngroup by m, container_name, namespace\norder by m;"
      }
     ]
    },
    {
     "title": "TOP DNS questions",
     "type": "table",
     "gridPos": { "h": 17, "w": 12, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "select count(*) total, dns_questions[1] q1 from events\nwhere $__timeFilter(ts) and name='net_packet_dns'\ngroup by q1\norder by total desc;",
       "selectedFormat": 1
      }
     ]
    },
    {
     "title": "TOP DNS answers",
     "type": "table",
     "gridPos": { "h": 17, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "rawSql": "select count(*) total, dns_answers[1] q1 from events\nwhere $__timeFilter(ts) and name='net_packet_dns' and dns_answers!='[]'\ngroup by q1\norder by total desc;",
       "selectedFormat": 1
      }
     ]
    }
   ]
  },
  {
   "title": "Exec events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from events where kind='exec'"
      }
     ]
    },
    {
     "title": "TOP Execs",
     "type": "table",
     "gridPos": { "h": 31, "w": 14, "x": 10, "y": 19 },
     "targets": [
      {
       "rawSql": "select count(*) total, file_path, args from events\nwhere $__timeFilter(ts) and kind='exec'\ngroup by file_path, args\norder by total desc\nlimit 100",
       "selectedFormat": 1
      }
     ]
    },
    {
     "title": "Exec events",
     "type": "timeseries",
     "gridPos": { "h": 25, "w": 10, "x": 0, "y": 25 },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) m, count(*) total, container_name, namespace from events\nwhere $__timeFilter(ts) and kind='exec'\ngroup by m, container_name, namespace\norder by m;"
      }
     ]
    }
   ]
  },
  {
   "title": "Security events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 13, "w": 4, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from events where kind='security'"
      }
     ]
    },
    {
     "title": "Security events",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 20, "x": 4, "y": 20 },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) m, count(*) total, name from events\nwhere $__timeFilter(ts) and kind='security'\ngroup by m, name\norder by m;"
      }
     ]
    }
   ]
  },
  { "title": "TCP Connects", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Total events",
   "type": "stat",
   "gridPos": { "h": 16, "w": 4, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "select count(*) from events where name='net_packet_tcp'"
    }
   ]
  },
  {
   "title": "TCP Connections by namespace",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 9, "x": 4, "y": 50 },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) m, count(*) total, namespace from events\nwhere $__timeFilter(ts) and name='net_packet_tcp'\ngroup by m, namespace\norder by m;"
    }
   ]
  },
  {
   "title": "Destination IP",
   "type": "table",
   "gridPos": { "h": 16, "w": 3, "x": 13, "y": 50 },
   "targets": [
    {
     "rawSql": "select count(*) total, IPv4NumToStringClassC(dst_ip) ip from events\nwhere $__timeFilter(ts) and name='net_packet_tcp'\ngroup by ip\norder by total desc;",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Destination Ports",
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 16, "y": 50 },
   "targets": [
    {
     "rawSql": "select count(*) total, dst_port from events\nwhere $__timeFilter(ts) and name='net_packet_tcp'\ngroup by dst_port\norder by total desc;",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "TCP Flags",
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 20, "y": 50 },
   "targets": [
    {
     "rawSql": "select count(*) total,\n       if(greater(bitAnd(flags, 1),0), 'FIN|', '') ||\n       if(greater(bitAnd(flags, 2),0), 'SYN|', '') ||\n       if(greater(bitAnd(flags, 16),0), 'ACK|', '') ||\n       if(greater(bitAnd(flags, 4),0), 'RST|', '') flags_str\nfrom events\nwhere $__timeFilter(ts) and kind='net' and name='net_packet_tcp'\ngroup by flags_str\norder by total desc;",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "File modification",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 16, "w": 4, "x": 0, "y": 22 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from events where name='file_modification'"
      }
     ]
    },
    {
     "title": "File paths (Top 100)",
     "type": "table",
     "gridPos": { "h": 16, "w": 20, "x": 4, "y": 22 },
     "targets": [
      {
       "rawSql": "select count(*) total, file_path from events\nwhere $__timeFilter(ts) and name='file_modification'\ngroup by file_path\norder by total desc\nlimit 100;",
       "selectedFormat": 1
      }
     ]
    }
   ]
  },
  {
   "title": "Kube events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total events",
     "type": "stat",
     "gridPos": { "h": 14, "w": 4, "x": 0, "y": 23 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "select count(*) from events where kind='kube'"
      }
     ]
    },
    {
     "title": "Kube events by type",
     "type": "table",
     "gridPos": { "h": 14, "w": 11, "x": 4, "y": 23 },
     "targets": [
      {
       "rawSql": "select count(*) total, name, severity from events\nwhere kind='kube'\ngroup by name, severity\norder by total desc;",
       "selectedFormat": 1
      }
     ]
    },
    {
     "title": "Kube events by severity",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 9, "x": 15, "y": 23 },
     "targets": [
      {
       "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) m, count(*) total, severity from events\nwhere $__timeFilter(ts) and kind='kube'\ngroup by m, severity\norder by m;\n"
      }
     ]
    }
   ]
  }
 ]
}