apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: castai-kvisor-agent
  namespace: castai-agent
spec:
  namespaceSelector:
    matchNames:
      - castai-agent
  podMetricsEndpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-kvisor-agent
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: castai-kvisor-controller
  namespace: castai-agent
spec:
  namespaceSelector:
    matchNames:
      - castai-agent
  podMetricsEndpoints:
    - honorLabels: true
      path: /metrics
      port: metrics
      scheme: http
      scrapeTimeout: 30s
  selector:
    matchLabels:
      app.kubernetes.io/name: castai-kvisor-controller
