// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfNetcontextVal struct{ Comm [16]uint8 }

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	CgroupConnect4        *ebpf.ProgramSpec `ebpf:"cgroup_connect4"`
	CgroupSkbEgress       *ebpf.ProgramSpec `ebpf:"cgroup_skb_egress"`
	CgroupSkbIngress      *ebpf.ProgramSpec `ebpf:"cgroup_skb_ingress"`
	CgroupSockCreate      *ebpf.ProgramSpec `ebpf:"cgroup_sock_create"`
	CgroupSockRelease     *ebpf.ProgramSpec `ebpf:"cgroup_sock_release"`
	TraceInetSockSetState *ebpf.ProgramSpec `ebpf:"trace_inet_sock_set_state"`
	TraceSecuritySkClone  *ebpf.ProgramSpec `ebpf:"trace_security_sk_clone"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	Events     *ebpf.MapSpec `ebpf:"events"`
	Netcontext *ebpf.MapSpec `ebpf:"netcontext"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
	TRACE_EVENT_FL_TRACEPOINT     *ebpf.VariableSpec `ebpf:"TRACE_EVENT_FL_TRACEPOINT"`
	TRACE_EVENT_FL_TRACEPOINT_BIT *ebpf.VariableSpec `ebpf:"TRACE_EVENT_FL_TRACEPOINT_BIT"`
	Unused                        *ebpf.VariableSpec `ebpf:"unused"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	Events     *ebpf.Map `ebpf:"events"`
	Netcontext *ebpf.Map `ebpf:"netcontext"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.Events,
		m.Netcontext,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
	TRACE_EVENT_FL_TRACEPOINT     *ebpf.Variable `ebpf:"TRACE_EVENT_FL_TRACEPOINT"`
	TRACE_EVENT_FL_TRACEPOINT_BIT *ebpf.Variable `ebpf:"TRACE_EVENT_FL_TRACEPOINT_BIT"`
	Unused                        *ebpf.Variable `ebpf:"unused"`
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	CgroupConnect4        *ebpf.Program `ebpf:"cgroup_connect4"`
	CgroupSkbEgress       *ebpf.Program `ebpf:"cgroup_skb_egress"`
	CgroupSkbIngress      *ebpf.Program `ebpf:"cgroup_skb_ingress"`
	CgroupSockCreate      *ebpf.Program `ebpf:"cgroup_sock_create"`
	CgroupSockRelease     *ebpf.Program `ebpf:"cgroup_sock_release"`
	TraceInetSockSetState *ebpf.Program `ebpf:"trace_inet_sock_set_state"`
	TraceSecuritySkClone  *ebpf.Program `ebpf:"trace_security_sk_clone"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.CgroupConnect4,
		p.CgroupSkbEgress,
		p.CgroupSkbIngress,
		p.CgroupSockCreate,
		p.CgroupSockRelease,
		p.TraceInetSockSetState,
		p.TraceSecuritySkClone,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
