{{- if .Values.agent.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kvisor.agent.fullname" . }}-kepler
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kvisor.agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: kepler
  annotations:
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: kepler-metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "kvisor.agent.selectorLabels" . | nindent 4 }}
{{- end }}
