apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kvisor.labels" . | nindent 4}}
data:
  {{- if .Values.castai.apiKey }}
  CASTAI_API_KEY: {{ required "castai.apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
  CASTAI_API_GRPC_ADDR: {{ if .Values.mockServer.enabled -}}
    {{ (printf "%s:8443" (include "kvisor.castaiMockServer.service" .)) | b64enc | quote }}
  {{- else -}}
    {{ required "castai.grpcAddr must be provided" .Values.castai.grpcAddr | b64enc | quote }}
  {{- end }}
  CASTAI_CLUSTER_ID: {{ required "castai.clusterID must be provided" .Values.castai.clusterID | b64enc | quote }}
  {{- end }}
