// Code generated by tools/codegen; DO NOT EDIT.

package types

type Args interface {
  args()
}

// internalArgs is a marker type to distinguish Args interface from basically any
type internalArgs struct{}

func (c internalArgs) args() {}

type ReadArgs struct {
  internalArgs

  Fd int32
  Buf uintptr
  Count uint64
}

type WriteArgs struct {
  internalArgs

  Fd int32
  Buf uintptr
  Count uint64
}

type OpenArgs struct {
  internalArgs

  Pathname string
  Flags int32
  Mode uint32
}

type CloseArgs struct {
  internalArgs

  Fd int32
}

type StatArgs struct {
  internalArgs

  Pathname string
  Statbuf uintptr
}

type FstatArgs struct {
  internalArgs

  Fd int32
  Statbuf uintptr
}

type LstatArgs struct {
  internalArgs

  Pathname string
  Statbuf uintptr
}

type PollArgs struct {
  internalArgs

  Fds uintptr
  Nfds uint32
  Timeout int32
}

type LseekArgs struct {
  internalArgs

  Fd int32
  Offset uint64
  Whence uint32
}

type MmapArgs struct {
  internalArgs

  Addr uintptr
  Length uint64
  Prot int32
  Flags int32
  Fd int32
  Off uint64
}

type MprotectArgs struct {
  internalArgs

  Addr uintptr
  Len uint64
  Prot int32
}

type MunmapArgs struct {
  internalArgs

  Addr uintptr
  Length uint64
}

type BrkArgs struct {
  internalArgs

  Addr uintptr
}

type RtSigactionArgs struct {
  internalArgs

  Signum int32
  Act uintptr
  Oldact uintptr
  Sigsetsize uint64
}

type RtSigprocmaskArgs struct {
  internalArgs

  How int32
  Set uintptr
  Oldset uintptr
  Sigsetsize uint64
}

type RtSigreturnArgs struct {
  internalArgs
}

type IoctlArgs struct {
  internalArgs

  Fd int32
  Request uint64
  Arg uint64
}

type Pread64Args struct {
  internalArgs

  Fd int32
  Buf uintptr
  Count uint64
  Offset uint64
}

type Pwrite64Args struct {
  internalArgs

  Fd int32
  Buf uintptr
  Count uint64
  Offset uint64
}

type ReadvArgs struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt int32
}

type WritevArgs struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt int32
}

type AccessArgs struct {
  internalArgs

  Pathname string
  Mode int32
}

type PipeArgs struct {
  internalArgs

  Pipefd [2]int32
}

type SelectArgs struct {
  internalArgs

  Nfds int32
  Readfds uintptr
  Writefds uintptr
  Exceptfds uintptr
  Timeout uintptr
}

type SchedYieldArgs struct {
  internalArgs
}

type MremapArgs struct {
  internalArgs

  OldAddress uintptr
  OldSize uint64
  NewSize uint64
  Flags int32
  NewAddress uintptr
}

type MsyncArgs struct {
  internalArgs

  Addr uintptr
  Length uint64
  Flags int32
}

type MincoreArgs struct {
  internalArgs

  Addr uintptr
  Length uint64
  Vec uintptr
}

type MadviseArgs struct {
  internalArgs

  Addr uintptr
  Length uint64
  Advice int32
}

type ShmgetArgs struct {
  internalArgs

  Key int32
  Size uint64
  Shmflg int32
}

type ShmatArgs struct {
  internalArgs

  Shmid int32
  Shmaddr uintptr
  Shmflg int32
}

type ShmctlArgs struct {
  internalArgs

  Shmid int32
  Cmd int32
  Buf uintptr
}

type DupArgs struct {
  internalArgs

  Oldfd int32
}

type Dup2Args struct {
  internalArgs

  Oldfd int32
  Newfd int32
}

type PauseArgs struct {
  internalArgs
}

type NanosleepArgs struct {
  internalArgs

  Req float64
  Rem float64
}

type GetitimerArgs struct {
  internalArgs

  Which int32
  CurrValue uintptr
}

type AlarmArgs struct {
  internalArgs

  Seconds uint32
}

type SetitimerArgs struct {
  internalArgs

  Which int32
  NewValue uintptr
  OldValue uintptr
}

type GetpidArgs struct {
  internalArgs
}

type SendfileArgs struct {
  internalArgs

  OutFd int32
  InFd int32
  Offset uintptr
  Count uint64
}

type SocketArgs struct {
  internalArgs

  Domain int32
  Type int32
  Protocol int32
}

type ConnectArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen int32
}

type AcceptArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen uintptr
}

type SendtoArgs struct {
  internalArgs

  Sockfd int32
  Buf uintptr
  Len uint64
  Flags int32
  DestAddr Sockaddr
  Addrlen int32
}

type RecvfromArgs struct {
  internalArgs

  Sockfd int32
  Buf uintptr
  Len uint64
  Flags int32
  SrcAddr Sockaddr
  Addrlen uintptr
}

type SendmsgArgs struct {
  internalArgs

  Sockfd int32
  Msg uintptr
  Flags int32
}

type RecvmsgArgs struct {
  internalArgs

  Sockfd int32
  Msg uintptr
  Flags int32
}

type ShutdownArgs struct {
  internalArgs

  Sockfd int32
  How int32
}

type BindArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen int32
}

type ListenArgs struct {
  internalArgs

  Sockfd int32
  Backlog int32
}

type GetsocknameArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen uintptr
}

type GetpeernameArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen uintptr
}

type SocketpairArgs struct {
  internalArgs

  Domain int32
  Type int32
  Protocol int32
  Sv [2]int32
}

type SetsockoptArgs struct {
  internalArgs

  Sockfd int32
  Level int32
  Optname int32
  Optval uintptr
  Optlen int32
}

type GetsockoptArgs struct {
  internalArgs

  Sockfd int32
  Level int32
  Optname int32
  Optval uintptr
  Optlen uintptr
}

type CloneArgs struct {
  internalArgs

  Flags uint64
  Stack uintptr
  ParentTid uintptr
  ChildTid uintptr
  Tls uint64
}

type ForkArgs struct {
  internalArgs
}

type VforkArgs struct {
  internalArgs
}

type ExecveArgs struct {
  internalArgs

  Pathname string
  Argv []string
}

type ExitArgs struct {
  internalArgs

  Status int32
}

type Wait4Args struct {
  internalArgs

  Pid int32
  Wstatus uintptr
  Options int32
  Rusage uintptr
}

type KillArgs struct {
  internalArgs

  Pid int32
  Sig int32
}

type UnameArgs struct {
  internalArgs

  Buf uintptr
}

type SemgetArgs struct {
  internalArgs

  Key int32
  Nsems int32
  Semflg int32
}

type SemopArgs struct {
  internalArgs

  Semid int32
  Sops uintptr
  Nsops uint64
}

type SemctlArgs struct {
  internalArgs

  Semid int32
  Semnum int32
  Cmd int32
  Arg uint64
}

type ShmdtArgs struct {
  internalArgs

  Shmaddr uintptr
}

type MsggetArgs struct {
  internalArgs

  Key int32
  Msgflg int32
}

type MsgsndArgs struct {
  internalArgs

  Msqid int32
  Msgp uintptr
  Msgsz uint64
  Msgflg int32
}

type MsgrcvArgs struct {
  internalArgs

  Msqid int32
  Msgp uintptr
  Msgsz uint64
  Msgtyp int64
  Msgflg int32
}

type MsgctlArgs struct {
  internalArgs

  Msqid int32
  Cmd int32
  Buf uintptr
}

type FcntlArgs struct {
  internalArgs

  Fd int32
  Cmd int32
  Arg uint64
}

type FlockArgs struct {
  internalArgs

  Fd int32
  Operation int32
}

type FsyncArgs struct {
  internalArgs

  Fd int32
}

type FdatasyncArgs struct {
  internalArgs

  Fd int32
}

type TruncateArgs struct {
  internalArgs

  Path string
  Length uint64
}

type FtruncateArgs struct {
  internalArgs

  Fd int32
  Length uint64
}

type GetdentsArgs struct {
  internalArgs

  Fd int32
  Dirp uintptr
  Count uint32
}

type GetcwdArgs struct {
  internalArgs

  Buf string
  Size uint64
}

type ChdirArgs struct {
  internalArgs

  Path string
}

type FchdirArgs struct {
  internalArgs

  Fd int32
}

type RenameArgs struct {
  internalArgs

  Oldpath string
  Newpath string
}

type MkdirArgs struct {
  internalArgs

  Pathname string
  Mode uint32
}

type RmdirArgs struct {
  internalArgs

  Pathname string
}

type CreatArgs struct {
  internalArgs

  Pathname string
  Mode uint32
}

type LinkArgs struct {
  internalArgs

  Oldpath string
  Newpath string
}

type UnlinkArgs struct {
  internalArgs

  Pathname string
}

type SymlinkArgs struct {
  internalArgs

  Target string
  Linkpath string
}

type ReadlinkArgs struct {
  internalArgs

  Pathname string
  Buf string
  Bufsiz uint64
}

type ChmodArgs struct {
  internalArgs

  Pathname string
  Mode uint32
}

type FchmodArgs struct {
  internalArgs

  Fd int32
  Mode uint32
}

type ChownArgs struct {
  internalArgs

  Pathname string
  Owner int32
  Group int32
}

type FchownArgs struct {
  internalArgs

  Fd int32
  Owner int32
  Group int32
}

type LchownArgs struct {
  internalArgs

  Pathname string
  Owner int32
  Group int32
}

type UmaskArgs struct {
  internalArgs

  Mask uint32
}

type GettimeofdayArgs struct {
  internalArgs

  Tv uintptr
  Tz uintptr
}

type GetrlimitArgs struct {
  internalArgs

  Resource int32
  Rlim uintptr
}

type GetrusageArgs struct {
  internalArgs

  Who int32
  Usage uintptr
}

type SysinfoArgs struct {
  internalArgs

  Info uintptr
}

type TimesArgs struct {
  internalArgs

  Buf uintptr
}

type PtraceArgs struct {
  internalArgs

  Request int64
  Pid int32
  Addr uintptr
  Data uintptr
}

type GetuidArgs struct {
  internalArgs
}

type SyslogArgs struct {
  internalArgs

  Type int32
  Bufp string
  Len int32
}

type GetgidArgs struct {
  internalArgs
}

type SetuidArgs struct {
  internalArgs

  Uid int32
}

type SetgidArgs struct {
  internalArgs

  Gid int32
}

type GeteuidArgs struct {
  internalArgs
}

type GetegidArgs struct {
  internalArgs
}

type SetpgidArgs struct {
  internalArgs

  Pid int32
  Pgid int32
}

type GetppidArgs struct {
  internalArgs
}

type GetpgrpArgs struct {
  internalArgs
}

type SetsidArgs struct {
  internalArgs
}

type SetreuidArgs struct {
  internalArgs

  Ruid int32
  Euid int32
}

type SetregidArgs struct {
  internalArgs

  Rgid int32
  Egid int32
}

type GetgroupsArgs struct {
  internalArgs

  Size int32
  List uintptr
}

type SetgroupsArgs struct {
  internalArgs

  Size int32
  List uintptr
}

type SetresuidArgs struct {
  internalArgs

  Ruid int32
  Euid int32
  Suid int32
}

type GetresuidArgs struct {
  internalArgs

  Ruid uintptr
  Euid uintptr
  Suid uintptr
}

type SetresgidArgs struct {
  internalArgs

  Rgid int32
  Egid int32
  Sgid int32
}

type GetresgidArgs struct {
  internalArgs

  Rgid uintptr
  Egid uintptr
  Sgid uintptr
}

type GetpgidArgs struct {
  internalArgs

  Pid int32
}

type SetfsuidArgs struct {
  internalArgs

  Fsuid int32
}

type SetfsgidArgs struct {
  internalArgs

  Fsgid int32
}

type GetsidArgs struct {
  internalArgs

  Pid int32
}

type CapgetArgs struct {
  internalArgs

  Hdrp uintptr
  Datap uintptr
}

type CapsetArgs struct {
  internalArgs

  Hdrp uintptr
  Datap uintptr
}

type RtSigpendingArgs struct {
  internalArgs

  Set uintptr
  Sigsetsize uint64
}

type RtSigtimedwaitArgs struct {
  internalArgs

  Set uintptr
  Info uintptr
  Timeout float64
  Sigsetsize uint64
}

type RtSigqueueinfoArgs struct {
  internalArgs

  Tgid int32
  Sig int32
  Info uintptr
}

type RtSigsuspendArgs struct {
  internalArgs

  Mask uintptr
  Sigsetsize uint64
}

type SigaltstackArgs struct {
  internalArgs

  Ss uintptr
  OldSs uintptr
}

type UtimeArgs struct {
  internalArgs

  Filename string
  Times uintptr
}

type MknodArgs struct {
  internalArgs

  Pathname string
  Mode uint32
  Dev uint32
}

type UselibArgs struct {
  internalArgs

  Library string
}

type PersonalityArgs struct {
  internalArgs

  Persona uint64
}

type UstatArgs struct {
  internalArgs

  Dev uint32
  Ubuf uintptr
}

type StatfsArgs struct {
  internalArgs

  Path string
  Buf uintptr
}

type FstatfsArgs struct {
  internalArgs

  Fd int32
  Buf uintptr
}

type SysfsArgs struct {
  internalArgs

  Option int32
}

type GetpriorityArgs struct {
  internalArgs

  Which int32
  Who int32
}

type SetpriorityArgs struct {
  internalArgs

  Which int32
  Who int32
  Prio int32
}

type SchedSetparamArgs struct {
  internalArgs

  Pid int32
  Param uintptr
}

type SchedGetparamArgs struct {
  internalArgs

  Pid int32
  Param uintptr
}

type SchedSetschedulerArgs struct {
  internalArgs

  Pid int32
  Policy int32
  Param uintptr
}

type SchedGetschedulerArgs struct {
  internalArgs

  Pid int32
}

type SchedGetPriorityMaxArgs struct {
  internalArgs

  Policy int32
}

type SchedGetPriorityMinArgs struct {
  internalArgs

  Policy int32
}

type SchedRrGetIntervalArgs struct {
  internalArgs

  Pid int32
  Tp float64
}

type MlockArgs struct {
  internalArgs

  Addr uintptr
  Len uint64
}

type MunlockArgs struct {
  internalArgs

  Addr uintptr
  Len uint64
}

type MlockallArgs struct {
  internalArgs

  Flags int32
}

type MunlockallArgs struct {
  internalArgs
}

type VhangupArgs struct {
  internalArgs
}

type ModifyLdtArgs struct {
  internalArgs

  Func int32
  Ptr uintptr
  Bytecount uint64
}

type PivotRootArgs struct {
  internalArgs

  NewRoot string
  PutOld string
}

type SysctlArgs struct {
  internalArgs

  Args uintptr
}

type PrctlArgs struct {
  internalArgs

  Option int32
  Arg2 uint64
  Arg3 uint64
  Arg4 uint64
  Arg5 uint64
}

type ArchPrctlArgs struct {
  internalArgs

  Option int32
  Addr uint64
}

type AdjtimexArgs struct {
  internalArgs

  Buf uintptr
}

type SetrlimitArgs struct {
  internalArgs

  Resource int32
  Rlim uintptr
}

type ChrootArgs struct {
  internalArgs

  Path string
}

type SyncArgs struct {
  internalArgs
}

type AcctArgs struct {
  internalArgs

  Filename string
}

type SettimeofdayArgs struct {
  internalArgs

  Tv uintptr
  Tz uintptr
}

type MountArgs struct {
  internalArgs

  Source string
  Target string
  Filesystemtype string
  Mountflags uint64
  Data uintptr
}

type Umount2Args struct {
  internalArgs

  Target string
  Flags int32
}

type SwaponArgs struct {
  internalArgs

  Path string
  Swapflags int32
}

type SwapoffArgs struct {
  internalArgs

  Path string
}

type RebootArgs struct {
  internalArgs

  Magic int32
  Magic2 int32
  Cmd int32
  Arg uintptr
}

type SethostnameArgs struct {
  internalArgs

  Name string
  Len uint64
}

type SetdomainnameArgs struct {
  internalArgs

  Name string
  Len uint64
}

type IoplArgs struct {
  internalArgs

  Level int32
}

type IopermArgs struct {
  internalArgs

  From uint64
  Num uint64
  TurnOn int32
}

type CreateModuleArgs struct {
  internalArgs
}

type InitModuleArgs struct {
  internalArgs

  ModuleImage uintptr
  Len uint64
  ParamValues string
}

type DeleteModuleArgs struct {
  internalArgs

  Name string
  Flags int32
}

type GetKernelSymsArgs struct {
  internalArgs
}

type QueryModuleArgs struct {
  internalArgs
}

type QuotactlArgs struct {
  internalArgs

  Cmd int32
  Special string
  Id int32
  Addr uintptr
}

type NfsservctlArgs struct {
  internalArgs
}

type GetpmsgArgs struct {
  internalArgs
}

type PutpmsgArgs struct {
  internalArgs
}

type AfsArgs struct {
  internalArgs
}

type TuxcallArgs struct {
  internalArgs
}

type SecurityArgs struct {
  internalArgs
}

type GettidArgs struct {
  internalArgs
}

type ReadaheadArgs struct {
  internalArgs

  Fd int32
  Offset uint64
  Count uint64
}

type SetxattrArgs struct {
  internalArgs

  Path string
  Name string
  Value uintptr
  Size uint64
  Flags int32
}

type LsetxattrArgs struct {
  internalArgs

  Path string
  Name string
  Value uintptr
  Size uint64
  Flags int32
}

type FsetxattrArgs struct {
  internalArgs

  Fd int32
  Name string
  Value uintptr
  Size uint64
  Flags int32
}

type GetxattrArgs struct {
  internalArgs

  Path string
  Name string
  Value uintptr
  Size uint64
}

type LgetxattrArgs struct {
  internalArgs

  Path string
  Name string
  Value uintptr
  Size uint64
}

type FgetxattrArgs struct {
  internalArgs

  Fd int32
  Name string
  Value uintptr
  Size uint64
}

type ListxattrArgs struct {
  internalArgs

  Path string
  List string
  Size uint64
}

type LlistxattrArgs struct {
  internalArgs

  Path string
  List string
  Size uint64
}

type FlistxattrArgs struct {
  internalArgs

  Fd int32
  List string
  Size uint64
}

type RemovexattrArgs struct {
  internalArgs

  Path string
  Name string
}

type LremovexattrArgs struct {
  internalArgs

  Path string
  Name string
}

type FremovexattrArgs struct {
  internalArgs

  Fd int32
  Name string
}

type TkillArgs struct {
  internalArgs

  Tid int32
  Sig int32
}

type TimeArgs struct {
  internalArgs

  Tloc uintptr
}

type FutexArgs struct {
  internalArgs

  Uaddr uintptr
  FutexOp int32
  Val int32
  Timeout float64
  Uaddr2 uintptr
  Val3 int32
}

type SchedSetaffinityArgs struct {
  internalArgs

  Pid int32
  Cpusetsize uint64
  Mask uintptr
}

type SchedGetaffinityArgs struct {
  internalArgs

  Pid int32
  Cpusetsize uint64
  Mask uintptr
}

type SetThreadAreaArgs struct {
  internalArgs

  UInfo uintptr
}

type IoSetupArgs struct {
  internalArgs

  NrEvents uint32
  CtxIdp uintptr
}

type IoDestroyArgs struct {
  internalArgs

  CtxId uintptr
}

type IoGeteventsArgs struct {
  internalArgs

  CtxId uintptr
  MinNr int64
  Nr int64
  Events uintptr
  Timeout float64
}

type IoSubmitArgs struct {
  internalArgs

  CtxId uintptr
  Nr int64
  Iocbpp uintptr
}

type IoCancelArgs struct {
  internalArgs

  CtxId uintptr
  Iocb uintptr
  Result uintptr
}

type GetThreadAreaArgs struct {
  internalArgs

  UInfo uintptr
}

type LookupDcookieArgs struct {
  internalArgs

  Cookie uint64
  Buffer string
  Len uint64
}

type EpollCreateArgs struct {
  internalArgs

  Size int32
}

type EpollCtlOldArgs struct {
  internalArgs
}

type EpollWaitOldArgs struct {
  internalArgs
}

type RemapFilePagesArgs struct {
  internalArgs

  Addr uintptr
  Size uint64
  Prot int32
  Pgoff uint64
  Flags int32
}

type Getdents64Args struct {
  internalArgs

  Fd uint32
  Dirp uintptr
  Count uint32
}

type SetTidAddressArgs struct {
  internalArgs

  Tidptr uintptr
}

type RestartSyscallArgs struct {
  internalArgs
}

type SemtimedopArgs struct {
  internalArgs

  Semid int32
  Sops uintptr
  Nsops uint64
  Timeout float64
}

type Fadvise64Args struct {
  internalArgs

  Fd int32
  Offset uint64
  Len uint64
  Advice int32
}

type TimerCreateArgs struct {
  internalArgs

  Clockid int32
  Sevp uintptr
  TimerId uintptr
}

type TimerSettimeArgs struct {
  internalArgs

  TimerId int32
  Flags int32
  NewValue uintptr
  OldValue uintptr
}

type TimerGettimeArgs struct {
  internalArgs

  TimerId int32
  CurrValue uintptr
}

type TimerGetoverrunArgs struct {
  internalArgs

  TimerId int32
}

type TimerDeleteArgs struct {
  internalArgs

  TimerId int32
}

type ClockSettimeArgs struct {
  internalArgs

  Clockid int32
  Tp float64
}

type ClockGettimeArgs struct {
  internalArgs

  Clockid int32
  Tp float64
}

type ClockGetresArgs struct {
  internalArgs

  Clockid int32
  Res float64
}

type ClockNanosleepArgs struct {
  internalArgs

  Clockid int32
  Flags int32
  Request float64
  Remain float64
}

type ExitGroupArgs struct {
  internalArgs

  Status int32
}

type EpollWaitArgs struct {
  internalArgs

  Epfd int32
  Events uintptr
  Maxevents int32
  Timeout int32
}

type EpollCtlArgs struct {
  internalArgs

  Epfd int32
  Op int32
  Fd int32
  Event uintptr
}

type TgkillArgs struct {
  internalArgs

  Tgid int32
  Tid int32
  Sig int32
}

type UtimesArgs struct {
  internalArgs

  Filename string
  Times uintptr
}

type VserverArgs struct {
  internalArgs
}

type MbindArgs struct {
  internalArgs

  Addr uintptr
  Len uint64
  Mode int32
  Nodemask uintptr
  Maxnode uint64
  Flags uint32
}

type SetMempolicyArgs struct {
  internalArgs

  Mode int32
  Nodemask uintptr
  Maxnode uint64
}

type GetMempolicyArgs struct {
  internalArgs

  Mode uintptr
  Nodemask uintptr
  Maxnode uint64
  Addr uintptr
  Flags uint64
}

type MqOpenArgs struct {
  internalArgs

  Name string
  Oflag int32
  Mode uint32
  Attr uintptr
}

type MqUnlinkArgs struct {
  internalArgs

  Name string
}

type MqTimedsendArgs struct {
  internalArgs

  Mqdes int32
  MsgPtr string
  MsgLen uint64
  MsgPrio uint32
  AbsTimeout float64
}

type MqTimedreceiveArgs struct {
  internalArgs

  Mqdes int32
  MsgPtr string
  MsgLen uint64
  MsgPrio uintptr
  AbsTimeout float64
}

type MqNotifyArgs struct {
  internalArgs

  Mqdes int32
  Sevp uintptr
}

type MqGetsetattrArgs struct {
  internalArgs

  Mqdes int32
  Newattr uintptr
  Oldattr uintptr
}

type KexecLoadArgs struct {
  internalArgs

  Entry uint64
  NrSegments uint64
  Segments uintptr
  Flags uint64
}

type WaitidArgs struct {
  internalArgs

  Idtype int32
  Id int32
  Infop uintptr
  Options int32
  Rusage uintptr
}

type AddKeyArgs struct {
  internalArgs

  Type string
  Description string
  Payload uintptr
  Plen uint64
  Keyring int32
}

type RequestKeyArgs struct {
  internalArgs

  Type string
  Description string
  CalloutInfo string
  DestKeyring int32
}

type KeyctlArgs struct {
  internalArgs

  Operation int32
  Arg2 uint64
  Arg3 uint64
  Arg4 uint64
  Arg5 uint64
}

type IoprioSetArgs struct {
  internalArgs

  Which int32
  Who int32
  Ioprio int32
}

type IoprioGetArgs struct {
  internalArgs

  Which int32
  Who int32
}

type InotifyInitArgs struct {
  internalArgs
}

type InotifyAddWatchArgs struct {
  internalArgs

  Fd int32
  Pathname string
  Mask uint32
}

type InotifyRmWatchArgs struct {
  internalArgs

  Fd int32
  Wd int32
}

type MigratePagesArgs struct {
  internalArgs

  Pid int32
  Maxnode uint64
  OldNodes uintptr
  NewNodes uintptr
}

type OpenatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Flags int32
  Mode uint32
}

type MkdiratArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Mode uint32
}

type MknodatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Mode uint32
  Dev uint32
}

type FchownatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Owner int32
  Group int32
  Flags int32
}

type FutimesatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Times uintptr
}

type NewfstatatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Statbuf uintptr
  Flags int32
}

type UnlinkatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Flags int32
}

type RenameatArgs struct {
  internalArgs

  Olddirfd int32
  Oldpath string
  Newdirfd int32
  Newpath string
}

type LinkatArgs struct {
  internalArgs

  Olddirfd int32
  Oldpath string
  Newdirfd int32
  Newpath string
  Flags uint32
}

type SymlinkatArgs struct {
  internalArgs

  Target string
  Newdirfd int32
  Linkpath string
}

type ReadlinkatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Buf string
  Bufsiz int32
}

type FchmodatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Mode uint32
  Flags int32
}

type FaccessatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Mode int32
  Flags int32
}

type Pselect6Args struct {
  internalArgs

  Nfds int32
  Readfds uintptr
  Writefds uintptr
  Exceptfds uintptr
  Timeout float64
  Sigmask uintptr
}

type PpollArgs struct {
  internalArgs

  Fds uintptr
  Nfds uint32
  TmoP float64
  Sigmask uintptr
  Sigsetsize uint64
}

type UnshareArgs struct {
  internalArgs

  Flags int32
}

type SetRobustListArgs struct {
  internalArgs

  Head uintptr
  Len uint64
}

type GetRobustListArgs struct {
  internalArgs

  Pid int32
  HeadPtr uintptr
  LenPtr uintptr
}

type SpliceArgs struct {
  internalArgs

  FdIn int32
  OffIn uintptr
  FdOut int32
  OffOut uintptr
  Len uint64
  Flags uint32
}

type TeeArgs struct {
  internalArgs

  FdIn int32
  FdOut int32
  Len uint64
  Flags uint32
}

type SyncFileRangeArgs struct {
  internalArgs

  Fd int32
  Offset uint64
  Nbytes uint64
  Flags uint32
}

type VmspliceArgs struct {
  internalArgs

  Fd int32
  Iov uintptr
  NrSegs uint64
  Flags uint32
}

type MovePagesArgs struct {
  internalArgs

  Pid int32
  Count uint64
  Pages uintptr
  Nodes uintptr
  Status uintptr
  Flags int32
}

type UtimensatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Times float64
  Flags int32
}

type EpollPwaitArgs struct {
  internalArgs

  Epfd int32
  Events uintptr
  Maxevents int32
  Timeout int32
  Sigmask uintptr
  Sigsetsize uint64
}

type SignalfdArgs struct {
  internalArgs

  Fd int32
  Mask uintptr
  Flags int32
}

type TimerfdCreateArgs struct {
  internalArgs

  Clockid int32
  Flags int32
}

type EventfdArgs struct {
  internalArgs

  Initval uint32
  Flags int32
}

type FallocateArgs struct {
  internalArgs

  Fd int32
  Mode int32
  Offset uint64
  Len uint64
}

type TimerfdSettimeArgs struct {
  internalArgs

  Fd int32
  Flags int32
  NewValue uintptr
  OldValue uintptr
}

type TimerfdGettimeArgs struct {
  internalArgs

  Fd int32
  CurrValue uintptr
}

type Accept4Args struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
  Addrlen uintptr
  Flags int32
}

type Signalfd4Args struct {
  internalArgs

  Fd int32
  Mask uintptr
  Sizemask uint64
  Flags int32
}

type Eventfd2Args struct {
  internalArgs

  Initval uint32
  Flags int32
}

type EpollCreate1Args struct {
  internalArgs

  Flags int32
}

type Dup3Args struct {
  internalArgs

  Oldfd int32
  Newfd int32
  Flags int32
}

type Pipe2Args struct {
  internalArgs

  Pipefd [2]int32
  Flags int32
}

type InotifyInit1Args struct {
  internalArgs

  Flags int32
}

type PreadvArgs struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt uint64
  PosL uint64
  PosH uint64
}

type PwritevArgs struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt uint64
  PosL uint64
  PosH uint64
}

type RtTgsigqueueinfoArgs struct {
  internalArgs

  Tgid int32
  Tid int32
  Sig int32
  Info uintptr
}

type PerfEventOpenArgs struct {
  internalArgs

  Attr uintptr
  Pid int32
  Cpu int32
  GroupFd int32
  Flags uint64
}

type RecvmmsgArgs struct {
  internalArgs

  Sockfd int32
  Msgvec uintptr
  Vlen uint32
  Flags int32
  Timeout float64
}

type FanotifyInitArgs struct {
  internalArgs

  Flags uint32
  EventFFlags uint32
}

type FanotifyMarkArgs struct {
  internalArgs

  FanotifyFd int32
  Flags uint32
  Mask uint64
  Dirfd int32
  Pathname string
}

type Prlimit64Args struct {
  internalArgs

  Pid int32
  Resource int32
  NewLimit uintptr
  OldLimit uintptr
}

type NameToHandleAtArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Handle uintptr
  MountId uintptr
  Flags int32
}

type OpenByHandleAtArgs struct {
  internalArgs

  MountFd int32
  Handle uintptr
  Flags int32
}

type ClockAdjtimeArgs struct {
  internalArgs

  ClkId int32
  Buf uintptr
}

type SyncfsArgs struct {
  internalArgs

  Fd int32
}

type SendmmsgArgs struct {
  internalArgs

  Sockfd int32
  Msgvec uintptr
  Vlen uint32
  Flags int32
}

type SetnsArgs struct {
  internalArgs

  Fd int32
  Nstype int32
}

type GetcpuArgs struct {
  internalArgs

  Cpu uintptr
  Node uintptr
  Tcache uintptr
}

type ProcessVmReadvArgs struct {
  internalArgs

  Pid int32
  LocalIov uintptr
  Liovcnt uint64
  RemoteIov uintptr
  Riovcnt uint64
  Flags uint64
}

type ProcessVmWritevArgs struct {
  internalArgs

  Pid int32
  LocalIov uintptr
  Liovcnt uint64
  RemoteIov uintptr
  Riovcnt uint64
  Flags uint64
}

type KcmpArgs struct {
  internalArgs

  Pid1 int32
  Pid2 int32
  Type int32
  Idx1 uint64
  Idx2 uint64
}

type FinitModuleArgs struct {
  internalArgs

  Fd int32
  ParamValues string
  Flags int32
}

type SchedSetattrArgs struct {
  internalArgs

  Pid int32
  Attr uintptr
  Flags uint32
}

type SchedGetattrArgs struct {
  internalArgs

  Pid int32
  Attr uintptr
  Size uint32
  Flags uint32
}

type Renameat2Args struct {
  internalArgs

  Olddirfd int32
  Oldpath string
  Newdirfd int32
  Newpath string
  Flags uint32
}

type SeccompArgs struct {
  internalArgs

  Operation uint32
  Flags uint32
  Args uintptr
}

type GetrandomArgs struct {
  internalArgs

  Buf uintptr
  Buflen uint64
  Flags uint32
}

type MemfdCreateArgs struct {
  internalArgs

  Name string
  Flags uint32
}

type KexecFileLoadArgs struct {
  internalArgs

  KernelFd int32
  InitrdFd int32
  CmdlineLen uint64
  Cmdline string
  Flags uint64
}

type BpfArgs struct {
  internalArgs

  Cmd int32
  Attr uintptr
  Size uint32
}

type ExecveatArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Argv []string
  Flags int32
}

type UserfaultfdArgs struct {
  internalArgs

  Flags int32
}

type MembarrierArgs struct {
  internalArgs

  Cmd int32
  Flags int32
}

type Mlock2Args struct {
  internalArgs

  Addr uintptr
  Len uint64
  Flags int32
}

type CopyFileRangeArgs struct {
  internalArgs

  FdIn int32
  OffIn uintptr
  FdOut int32
  OffOut uintptr
  Len uint64
  Flags uint32
}

type Preadv2Args struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt uint64
  PosL uint64
  PosH uint64
  Flags int32
}

type Pwritev2Args struct {
  internalArgs

  Fd int32
  Iov uintptr
  Iovcnt uint64
  PosL uint64
  PosH uint64
  Flags int32
}

type PkeyMprotectArgs struct {
  internalArgs

  Addr uintptr
  Len uint64
  Prot int32
  Pkey int32
}

type PkeyAllocArgs struct {
  internalArgs

  Flags uint32
  AccessRights uint64
}

type PkeyFreeArgs struct {
  internalArgs

  Pkey int32
}

type StatxArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Flags int32
  Mask uint32
  Statxbuf uintptr
}

type IoPgeteventsArgs struct {
  internalArgs

  CtxId uintptr
  MinNr int64
  Nr int64
  Events uintptr
  Timeout float64
  Usig uintptr
}

type RseqArgs struct {
  internalArgs

  Rseq uintptr
  RseqLen uint32
  Flags int32
  Sig uint32
}

type PidfdSendSignalArgs struct {
  internalArgs

  Pidfd int32
  Sig int32
  Info uintptr
  Flags uint32
}

type IoUringSetupArgs struct {
  internalArgs

  Entries uint32
  P uintptr
}

type IoUringEnterArgs struct {
  internalArgs

  Fd uint32
  ToSubmit uint32
  MinComplete uint32
  Flags uint32
  Sig uintptr
}

type IoUringRegisterArgs struct {
  internalArgs

  Fd uint32
  Opcode uint32
  Arg uintptr
  NrArgs uint32
}

type OpenTreeArgs struct {
  internalArgs

  Dfd int32
  Filename string
  Flags uint32
}

type MoveMountArgs struct {
  internalArgs

  FromDfd int32
  FromPath string
  ToDfd int32
  ToPath string
  Flags uint32
}

type FsopenArgs struct {
  internalArgs

  Fsname string
  Flags uint32
}

type FsconfigArgs struct {
  internalArgs

  FsFd uintptr
  Cmd uint32
  Key string
  Value uintptr
  Aux int32
}

type FsmountArgs struct {
  internalArgs

  Fsfd int32
  Flags uint32
  MsFlags uint32
}

type FspickArgs struct {
  internalArgs

  Dirfd int32
  Pathname string
  Flags uint32
}

type PidfdOpenArgs struct {
  internalArgs

  Pid int32
  Flags uint32
}

type Clone3Args struct {
  internalArgs

  ClArgs uintptr
  Size uint64
}

type CloseRangeArgs struct {
  internalArgs

  First uint32
  Last uint32
}

type Openat2Args struct {
  internalArgs

  Dirfd int32
  Pathname string
  How uintptr
  Size uint64
}

type PidfdGetfdArgs struct {
  internalArgs

  Pidfd int32
  Targetfd int32
  Flags uint32
}

type Faccessat2Args struct {
  internalArgs

  Fd int32
  Path string
  Mode int32
  Flag int32
}

type ProcessMadviseArgs struct {
  internalArgs

  Pidfd int32
  Addr uintptr
  Length uint64
  Advice int32
  Flags uint64
}

type EpollPwait2Args struct {
  internalArgs

  Fd int32
  Events uintptr
  Maxevents int32
  Timeout float64
  Sigset uintptr
}

type MountSetattArgs struct {
  internalArgs

  Dfd int32
  Path string
  Flags uint32
  Uattr uintptr
  Usize uint64
}

type QuotactlFdArgs struct {
  internalArgs

  Fd uint32
  Cmd uint32
  Id uintptr
  Addr uintptr
}

type LandlockCreateRulesetArgs struct {
  internalArgs

  Attr uintptr
  Size uint64
  Flags uint32
}

type LandlockAddRuleArgs struct {
  internalArgs

  RulesetFd int32
  RuleType uintptr
  RuleAttr uintptr
  Flags uint32
}

type LandloclRestrictSetArgs struct {
  internalArgs

  RulesetFd int32
  Flags uint32
}

type MemfdSecretArgs struct {
  internalArgs

  Flags uint32
}

type ProcessMreleaseArgs struct {
  internalArgs

  Pidfd int32
  Flags uint32
}

type WaitpidArgs struct {
  internalArgs

  Pid int32
  Status uintptr
  Options int32
}

type OldfstatArgs struct {
  internalArgs
}

type BreakArgs struct {
  internalArgs
}

type OldstatArgs struct {
  internalArgs

  Filename string
  Statbuf uintptr
}

type UmountArgs struct {
  internalArgs

  Target string
}

type StimeArgs struct {
  internalArgs

  T uintptr
}

type SttyArgs struct {
  internalArgs
}

type GttyArgs struct {
  internalArgs
}

type NiceArgs struct {
  internalArgs

  Inc int32
}

type FtimeArgs struct {
  internalArgs
}

type ProfArgs struct {
  internalArgs
}

type SignalArgs struct {
  internalArgs

  Signum int32
  Handler uintptr
}

type LockArgs struct {
  internalArgs
}

type MpxArgs struct {
  internalArgs
}

type UlimitArgs struct {
  internalArgs
}

type OldoldunameArgs struct {
  internalArgs

  Name uintptr
}

type SigactionArgs struct {
  internalArgs

  Sig int32
  Act uintptr
  Oact uintptr
}

type SgetmaskArgs struct {
  internalArgs
}

type SsetmaskArgs struct {
  internalArgs

  Newmask int64
}

type SigsuspendArgs struct {
  internalArgs

  Mask uintptr
}

type SigpendingArgs struct {
  internalArgs

  Set uintptr
}

type OldlstatArgs struct {
  internalArgs

  Pathname string
  Statbuf uintptr
}

type ReaddirArgs struct {
  internalArgs

  Fd uint32
  Dirp uintptr
  Count uint32
}

type ProfilArgs struct {
  internalArgs
}

type SocketcallArgs struct {
  internalArgs

  Call int32
  Args uintptr
}

type OldunameArgs struct {
  internalArgs

  Buf uintptr
}

type IdleArgs struct {
  internalArgs
}

type Vm86oldArgs struct {
  internalArgs

  Info uintptr
}

type IpcArgs struct {
  internalArgs

  Call uint32
  First int32
  Second uint64
  Third uint64
  Ptr uintptr
  Fifth int64
}

type SigreturnArgs struct {
  internalArgs
}

type SigprocmaskArgs struct {
  internalArgs

  How int32
  Set uintptr
  Oldset uintptr
}

type BdflushArgs struct {
  internalArgs
}

type Afs_syscallArgs struct {
  internalArgs
}

type LlseekArgs struct {
  internalArgs

  Fd uint32
  OffsetHigh uint64
  OffsetLow uint64
  Result uintptr
  Whence uint32
}

type OldSelectArgs struct {
  internalArgs

  Nfds int32
  Readfds uintptr
  Writefds uintptr
  Exceptfds uintptr
  Timeout uintptr
}

type Vm86Args struct {
  internalArgs

  Fn uint64
  V86 uintptr
}

type OldGetrlimitArgs struct {
  internalArgs

  Resource int32
  Rlim uintptr
}

type Mmap2Args struct {
  internalArgs

  Addr uint64
  Length uint64
  Prot uint64
  Flags uint64
  Fd uint64
  Pgoffset uint64
}

type Truncate64Args struct {
  internalArgs

  Path string
  Length uint64
}

type Ftruncate64Args struct {
  internalArgs

  Fd int32
  Length uint64
}

type Stat64Args struct {
  internalArgs

  Pathname string
  Statbuf uintptr
}

type Lstat64Args struct {
  internalArgs

  Pathname string
  Statbuf uintptr
}

type Fstat64Args struct {
  internalArgs

  Fd int32
  Statbuf uintptr
}

type Lchown16Args struct {
  internalArgs

  Pathname string
  Owner uintptr
  Group uintptr
}

type Getuid16Args struct {
  internalArgs
}

type Getgid16Args struct {
  internalArgs
}

type Geteuid16Args struct {
  internalArgs
}

type Getegid16Args struct {
  internalArgs
}

type Setreuid16Args struct {
  internalArgs

  Ruid uintptr
  Euid uintptr
}

type Setregid16Args struct {
  internalArgs

  Rgid uintptr
  Egid uintptr
}

type Getgroups16Args struct {
  internalArgs

  Size int32
  List uintptr
}

type Setgroups16Args struct {
  internalArgs

  Size uint64
  List uintptr
}

type Fchown16Args struct {
  internalArgs

  Fd uint32
  User uintptr
  Group uintptr
}

type Setresuid16Args struct {
  internalArgs

  Ruid uintptr
  Euid uintptr
  Suid uintptr
}

type Getresuid16Args struct {
  internalArgs

  Ruid uintptr
  Euid uintptr
  Suid uintptr
}

type Setresgid16Args struct {
  internalArgs

  Rgid uintptr
  Euid uintptr
  Suid uintptr
}

type Getresgid16Args struct {
  internalArgs

  Rgid uintptr
  Egid uintptr
  Sgid uintptr
}

type Chown16Args struct {
  internalArgs

  Pathname string
  Owner uintptr
  Group uintptr
}

type Setuid16Args struct {
  internalArgs

  Uid uintptr
}

type Setgid16Args struct {
  internalArgs

  Gid uintptr
}

type Setfsuid16Args struct {
  internalArgs

  Fsuid uintptr
}

type Setfsgid16Args struct {
  internalArgs

  Fsgid uintptr
}

type Fcntl64Args struct {
  internalArgs

  Fd int32
  Cmd int32
  Arg uint64
}

type Sendfile32Args struct {
  internalArgs

  OutFd int32
  InFd int32
  Offset uintptr
  Count uint64
}

type Statfs64Args struct {
  internalArgs

  Path string
  Sz uint64
  Buf uintptr
}

type Fstatfs64Args struct {
  internalArgs

  Fd int32
  Sz uint64
  Buf uintptr
}

type Fadvise64_64Args struct {
  internalArgs

  Fd int32
  Offset uint64
  Len uint64
  Advice int32
}

type ClockGettime32Args struct {
  internalArgs

  WhichClock int32
  Tp uintptr
}

type ClockSettime32Args struct {
  internalArgs

  WhichClock int32
  Tp uintptr
}

type ClockAdjtime64Args struct {
  internalArgs
}

type ClockGetresTime32Args struct {
  internalArgs

  WhichClock int32
  Tp uintptr
}

type ClockNanosleepTime32Args struct {
  internalArgs

  WhichClock int32
  Flags int32
  Rqtp uintptr
  Rmtp uintptr
}

type TimerGettime32Args struct {
  internalArgs

  TimerId int32
  Setting uintptr
}

type TimerSettime32Args struct {
  internalArgs

  TimerId int32
  Flags int32
  New uintptr
  Old uintptr
}

type TimerfdGettime32Args struct {
  internalArgs

  Ufd int32
  Otmr uintptr
}

type TimerfdSettime32Args struct {
  internalArgs

  Ufd int32
  Flags int32
  Utmr uintptr
  Otmr uintptr
}

type UtimensatTime32Args struct {
  internalArgs

  Dfd uint32
  Filename string
  T uintptr
  Flags int32
}

type Pselect6Time32Args struct {
  internalArgs

  N int32
  Inp uintptr
  Outp uintptr
  Exp uintptr
  Tsp uintptr
  Sig uintptr
}

type PpollTime32Args struct {
  internalArgs

  Ufds uintptr
  Nfds uint32
  Tsp uintptr
  Sigmask uintptr
  Sigsetsize uint64
}

type IoPgeteventsTime32Args struct {
  internalArgs
}

type RecvmmsgTime32Args struct {
  internalArgs

  Fd int32
  Mmsg uintptr
  Vlen uint32
  Flags uint32
  Timeout uintptr
}

type MqTimedsendTime32Args struct {
  internalArgs

  Mqdes int32
  UMsgPtr string
  MsgLen uint32
  MsgPrio uint32
  UAbsTimeout uintptr
}

type MqTimedreceiveTime32Args struct {
  internalArgs

  Mqdes int32
  UMsgPtr string
  MsgLen uint32
  UMsgPrio uintptr
  UAbsTimeout uintptr
}

type RtSigtimedwaitTime32Args struct {
  internalArgs

  Uthese uintptr
  Uinfo uintptr
  Uts uintptr
  Sigsetsize uint64
}

type FutexTime32Args struct {
  internalArgs

  Uaddr uintptr
  Op int32
  Val uint32
  Utime uintptr
  Uaddr2 uintptr
  Val3 uint32
}

type SchedRrGetInterval32Args struct {
  internalArgs

  Pid int32
  Interval uintptr
}

type SysEnterArgs struct {
  internalArgs

  Syscall int32
}

type SysExitArgs struct {
  internalArgs

  Syscall int32
}

type SchedProcessForkArgs struct {
  internalArgs

  ParentTid int32
  ParentNsTid int32
  ParentPid int32
  ParentNsPid int32
  ParentStartTime uint64
  ChildTid int32
  ChildNsTid int32
  ChildPid int32
  ChildNsPid int32
  ChildStartTime uint64
  UpParentTid int32
  UpParentNsTid int32
  UpParentPid int32
  UpParentNsPid int32
  UpParentStartTime uint64
  LeaderTid int32
  LeaderNsTid int32
  LeaderPid int32
  LeaderNsPid int32
  LeaderStartTime uint64
}

type SchedProcessExecArgs struct {
  internalArgs

  Filename string
  Filepath string
  Dev uint32
  Inode uint64
  Ctime uint64
  InodeMode uint16
  InterpreterPathname string
  InterpreterDev uint32
  InterpreterInode uint64
  InterpreterCtime uint64
  Argv []string
  Interp string
  StdinType uint16
  StdinPath string
  InvokedFromKernel int32
  Flags uint32
}

type SchedProcessExitArgs struct {
  internalArgs

  ExitCode int64
  ProcessGroupExit bool
}

type SchedSwitchArgs struct {
  internalArgs

  Cpu int32
  PrevTid int32
  PrevComm string
  NextTid int32
  NextComm string
}

type ProcessOomKilledArgs struct {
  internalArgs

  ExitCode int64
  ProcessGroupExit bool
}

type MagicWriteArgs struct {
  internalArgs

  Pathname string
  Bytes []byte
  Dev uint32
  Inode uint64
}

type CgroupMkdirArgs struct {
  internalArgs

  CgroupId uint64
  CgroupPath string
  HierarchyId uint32
}

type CgroupRmdirArgs struct {
  internalArgs

  CgroupId uint64
  CgroupPath string
  HierarchyId uint32
}

type SecuritySocketConnectArgs struct {
  internalArgs

  Sockfd int32
  Type int32
  RemoteAddr Sockaddr
}

type SocketDupArgs struct {
  internalArgs

  Oldfd int32
  Newfd int32
  RemoteAddr Sockaddr
}

type FileModificationArgs struct {
  internalArgs

  FilePath string
  Dev uint32
  Inode uint64
  OldCtime uint64
  NewCtime uint64
}

type TtyOpenArgs struct {
  internalArgs

  Path string
  Inode uint64
  InodeMode uint16
  Dev uint32
}

type TtyWriteArgs struct {
  internalArgs

  Path string
  Inode uint64
}

type NetPacketBaseArgs struct {
  internalArgs
}

type NetPacketIPBaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketTCPBaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketUDPBaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketICMPBaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketICMPv6BaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketDNSBaseArgs struct {
  internalArgs

  Payload *ProtoDNS
}

type NetPacketSOCKS5BaseArgs struct {
  internalArgs

  Payload []byte
}

type NetPacketSSHBaseArgs struct {
  internalArgs

  Payload *ProtoSSH
}

type SockSetStateArgs struct {
  internalArgs

  OldState uint32
  NewState uint32
  Tuple AddrTuple
}

type TrackSyscallStatsArgs struct {
  internalArgs
}

type NetFlowBaseArgs struct {
  internalArgs
}

type StdioViaSocketArgs struct {
  internalArgs

  Sockfd int32
  Addr Sockaddr
}

type TestEventArgs struct {
  internalArgs
}
