apiVersion: apps/v1
kind: Deployment
metadata:
  name: castai-kvisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  strategy:
    {{- .Values.updateStrategy | toYaml | nindent 4 }}
  {{- if .Values.leaderElectionEnabled }}
  replicas: {{ .Values.replicas }}
  {{- else}}
  replicas: 1
  {{- end}}
  selector:
    matchLabels:
      {{- include "castai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "castai.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.commonLabels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
        {{- if .Values.metrics.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{.Values.metrics.scrapePort}}"
        {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.commonAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: kvisor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_NAME
              value: {{ ((.Values.kvisor | default dict).serviceName | default "kvisor") | quote }}
            - name: SERVICE_PORT
              value: {{ ((.Values.kvisor | default dict).servicePort | default 7070) | quote }}
            - name: CERTS_DIR
              value: {{ ((.Values.kvisor | default dict).certsDir | default "/certs") | quote }}
            - name: CERTS_SECRET
              value: {{ ((.Values.kvisor | default dict).certsSecret | default "kvisor-certs") | quote }}
            - name: LEADER_ELECTION
              value: {{ .Values.leaderElectionEnabled | quote }}
            - name: POLICY_ENFORCEMENT_ENABLED
              value: {{ (.Values.policyEnforcement | default dict).enabled | quote }}
            - name: POLICY_ENFORCEMENT_WEBHOOK_NAME
              value: {{ (.Values.policyEnforcement | default dict).webhookName | quote }}
            - name: STATUS_PORT
              value: {{ ((.Values.kvisor | default dict).statusPort | default 7071) | quote }}
            - name: API_URL
              value: {{ .Values.castai.apiURL | quote }}
            - name: CLUSTER_ID
              value: {{ .Values.castai.clusterID | quote }}
          {{- range $k, $v := .Values.additionalEnv }}
            - name: {{ $k }}
              value: "{{ $v }}"
          {{- end }}
          envFrom:
            - secretRef:
                {{- if .Values.apiKeySecretRef }}
                name: {{ .Values.apiKeySecretRef }}
                {{- else }}
                name: castai-kvisor
                {{- end }}
                optional: false
            - configMapRef:
                name: castai-kvisor
          volumeMounts:
            - name: config
              mountPath: /etc/castai/config
            - mountPath: /certs
              name: certs
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.agentContainerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 6060
              name: http
              protocol: TCP
            - containerPort: {{ ((.Values.kvisor | default dict).servicePort | default 7070) }}
              name: webhook
              protocol: TCP
            - containerPort: {{ ((.Values.kvisor | default dict).statusPort | default 7071) }}
              name: status
              protocol: TCP
          livenessProbe:
            httpGet:
              port: status
              path: /healthz
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: status
              path: /readyz
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: config
          {{- if .Values.existingSecretForConfig }}
          secret:
            secretName: {{ .Values.existingSecretForConfig }}
          {{- else }}
          configMap:
            name: castai-kvisor
          {{- end }}
        - name: certs
          secret:
            secretName: {{ ((.Values.kvisor | default dict).certsSecret | default "kvisor-certs") | quote }}
