{{- if .Values.runtime.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "kvisor.runtime.name" . }}
  labels:
    {{- include "kvisor.runtime.labels" . | nindent 4 }}
    app.kubernetes.io/component: runtime
spec:
  selector:
    matchLabels:
      {{- include "kvisor.runtime.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kvisor.runtime.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "castai.serviceAccountName" . }}
      hostNetwork: true
      containers:
        - name: egressd
          securityContext:
            {{- toYaml .Values.runtime.securityContext | nindent 12 }}
          image: "{{ .Values.runtime.image.repository }}:{{ .Values.runtime.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.runtime.image.pullPolicy }}
          resources:
            {{- toYaml .Values.runtime.resources | nindent 12 }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      {{- with .Values.runtime.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtime.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.runtime.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
