{{- if or .Values.apiKey .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: castai-kvisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai.labels" . | nindent 4 }}
data:
  API_KEY: {{ required "castai.apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
{{- end }}
