{{- if or .Values.apiKey .Values.castai.apiKey }}
---
apiVersion: v1
kind: Secret
metadata:
  name: castai-kvisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "castai.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  API_KEY: {{ required "castai.apiKey must be provided" .Values.castai.apiKey | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.kvisor.certsSecret }}
  namespace: {{ .Release.Namespace }}
