apiVersion: v1
kind: Service
metadata:
  name: {{ ((.Values.kvisor | default dict).serviceName | default "kvisor") }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: castai-kvisor
  ports:
    - name: http
      protocol: TCP
      port: 6060
      targetPort: http
    {{- if (.Values.policyEnforcement | default dict).enabled }}
    - name: webhook
      protocol: TCP
      port: {{ ((.Values.kvisor | default dict).servicePort | default 7070) }}
      targetPort: webhook
    {{- end}}
