fullnameOverride: grafana
adminPassword: admin
grafana.ini:
  server:
    serve_from_sub_path: false
    root_url: /
  analytics:
    check_for_updates: false
  grafana_net:
    url: https://grafana.net
  log:
    mode: console
  auth.anonymous:
    enabled: true
    org_name: Main Org.
    org_role: Admin
  users:
    default_theme: light

persistence:
  type: pvc
  enabled: true
  # storageClassName: default
  accessModes:
    - ReadWriteOnce
  size: 1Gi

plugins:
  - grafana-clickhouse-datasource

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: ClickHouse
        type: grafana-clickhouse-datasource
        jsonData:
          defaultDatabase: kvisor
          port: 9000
          server: castai-kvisor-clickhouse.kvisor.svc.cluster.local.
          username: kvisor
          tlsSkipVerify: true
        secureJsonData:
          password: kvisor
      - name: prometheus
        type: prometheus
        url: http://prometheus-server.metrics.svc.cluster.local.
        access: proxy
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        url: http://pyroscope.metrics.svc.cluster.local.:4040/
#      - name: Loki
#        type: loki
#        url: http://kvisor-loki.kvisor-trace.svc.cluster.local.:3100
#        access: proxy
#        isDefault: true
