{
 "title": "Netflows",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exported data rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_send_total{}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kube IP info fetch errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_fetch_kube_ip_info_errors_total{}[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Export error rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_send_errors_total{}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Export queue drop rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(kvisor_agent_exporter_queue_dropped_total{}[1m])) by (exporter)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Kvisor netflow egress bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) AS period, namespace, sum(tx_bytes) V\nfrom netflows\nwhere ( ts >= $__fromTime AND ts <= $__toTime )\ngroup by period, namespace\norder by period, namespace"
    }
   ]
  },
  {
   "title": "Container egress bytes",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_bytes_total{image!=\"\", namespace!=\"kube-system\"}[1m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kvisor netflow egress packets",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select toStartOfInterval(ts, INTERVAL 1 minute) AS period, namespace, sum(tx_packets) V\nfrom netflows\nwhere ( ts >= $__fromTime AND ts <= $__toTime )\ngroup by period, namespace\norder by period, namespace"
    }
   ]
  },
  {
   "title": "Container egress packets",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(container_network_transmit_packets_total{image!=\"\", namespace!=\"kube-system\"}[1m])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}