apiVersion: apps/v1
kind: Deployment
metadata:
  name: mockapi
  namespace: kvisor
  labels:
    app.kubernetes.io/name: mockapi
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: mockapi
  replicas: 1
  strategy:
    rollingUpdate: {}
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mockapi
    spec:
      containers:
        - name: mockapi
          image: "mockapi"
          ports:
            - name: http
              containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: mockapi
  namespace: kvisor
  labels:
    app.kubernetes.io/name: mockapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: mockapi
