apiVersion: v1
kind: Pod
metadata:
  name: docker-pod
  namespace: default
spec:
  containers:
  - name: docker
    image: docker
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock
  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
