// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/v1/proxy/proxy.proto

package proxy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proxy_proxy_proto_rawDescGZIP(), []int{0}
}

type SendResponseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendResponseResult) Reset() {
	*x = SendResponseResult{}
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendResponseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendResponseResult) ProtoMessage() {}

func (x *SendResponseResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendResponseResult.ProtoReflect.Descriptor instead.
func (*SendResponseResult) Descriptor() ([]byte, []int) {
	return file_api_v1_proxy_proxy_proto_rawDescGZIP(), []int{1}
}

type HttpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Headers       []*Header              `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRequest) Reset() {
	*x = HttpRequest{}
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRequest) ProtoMessage() {}

func (x *HttpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRequest.ProtoReflect.Descriptor instead.
func (*HttpRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_proxy_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *HttpRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HttpRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HttpRequest) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type HttpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	StatusCode    int32                  `protobuf:"varint,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Headers       []*Header              `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	More          bool                   `protobuf:"varint,5,opt,name=more,proto3" json:"more,omitempty"`
	Error         string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpResponse) Reset() {
	*x = HttpResponse{}
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpResponse) ProtoMessage() {}

func (x *HttpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpResponse.ProtoReflect.Descriptor instead.
func (*HttpResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_proxy_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *HttpResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *HttpResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *HttpResponse) GetHeaders() []*Header {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HttpResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HttpResponse) GetMore() bool {
	if x != nil {
		return x.More
	}
	return false
}

func (x *HttpResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_proxy_proxy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_api_v1_proxy_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *Header) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Header) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_api_v1_proxy_proxy_proto protoreflect.FileDescriptor

const file_api_v1_proxy_proxy_proto_rawDesc = "" +
	"\n" +
	"\x18api/v1/proxy/proxy.proto\x12\bproxy.v1\"\x12\n" +
	"\x10SubscribeRequest\"\x14\n" +
	"\x12SendResponseResult\"\x98\x01\n" +
	"\vHttpRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12*\n" +
	"\aheaders\x18\x04 \x03(\v2\x10.proxy.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x05 \x01(\fR\x04body\"\xb8\x01\n" +
	"\fHttpResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1f\n" +
	"\vstatus_code\x18\x02 \x01(\x05R\n" +
	"statusCode\x12*\n" +
	"\aheaders\x18\x03 \x03(\v2\x10.proxy.v1.HeaderR\aheaders\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12\x12\n" +
	"\x04more\x18\x05 \x01(\bR\x04more\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\"2\n" +
	"\x06Header\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values2\x9f\x01\n" +
	"\x0fKubernetesProxy\x12B\n" +
	"\tSubscribe\x12\x1a.proxy.v1.SubscribeRequest\x1a\x15.proxy.v1.HttpRequest\"\x000\x01\x12H\n" +
	"\fSendResponse\x12\x16.proxy.v1.HttpResponse\x1a\x1c.proxy.v1.SendResponseResult\"\x00(\x01B'Z%github.com/castai/kvisor/api/v1/proxyb\x06proto3"

var (
	file_api_v1_proxy_proxy_proto_rawDescOnce sync.Once
	file_api_v1_proxy_proxy_proto_rawDescData []byte
)

func file_api_v1_proxy_proxy_proto_rawDescGZIP() []byte {
	file_api_v1_proxy_proxy_proto_rawDescOnce.Do(func() {
		file_api_v1_proxy_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_proxy_proxy_proto_rawDesc), len(file_api_v1_proxy_proxy_proto_rawDesc)))
	})
	return file_api_v1_proxy_proxy_proto_rawDescData
}

var file_api_v1_proxy_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_v1_proxy_proxy_proto_goTypes = []any{
	(*SubscribeRequest)(nil),   // 0: proxy.v1.SubscribeRequest
	(*SendResponseResult)(nil), // 1: proxy.v1.SendResponseResult
	(*HttpRequest)(nil),        // 2: proxy.v1.HttpRequest
	(*HttpResponse)(nil),       // 3: proxy.v1.HttpResponse
	(*Header)(nil),             // 4: proxy.v1.Header
}
var file_api_v1_proxy_proxy_proto_depIdxs = []int32{
	4, // 0: proxy.v1.HttpRequest.headers:type_name -> proxy.v1.Header
	4, // 1: proxy.v1.HttpResponse.headers:type_name -> proxy.v1.Header
	0, // 2: proxy.v1.KubernetesProxy.Subscribe:input_type -> proxy.v1.SubscribeRequest
	3, // 3: proxy.v1.KubernetesProxy.SendResponse:input_type -> proxy.v1.HttpResponse
	2, // 4: proxy.v1.KubernetesProxy.Subscribe:output_type -> proxy.v1.HttpRequest
	1, // 5: proxy.v1.KubernetesProxy.SendResponse:output_type -> proxy.v1.SendResponseResult
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_v1_proxy_proxy_proto_init() }
func file_api_v1_proxy_proxy_proto_init() {
	if File_api_v1_proxy_proxy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_proxy_proxy_proto_rawDesc), len(file_api_v1_proxy_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_proxy_proxy_proto_goTypes,
		DependencyIndexes: file_api_v1_proxy_proxy_proto_depIdxs,
		MessageInfos:      file_api_v1_proxy_proxy_proto_msgTypes,
	}.Build()
	File_api_v1_proxy_proxy_proto = out.File
	file_api_v1_proxy_proxy_proto_goTypes = nil
	file_api_v1_proxy_proxy_proto_depIdxs = nil
}
