// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: api/v1/proxy/proxy.proto

package proxy

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClusterProxy_Subscribe_FullMethodName    = "/cluster_proxy.v1alpha1.ClusterProxy/Subscribe"
	ClusterProxy_SendResponse_FullMethodName = "/cluster_proxy.v1alpha1.ClusterProxy/SendResponse"
)

// ClusterProxyClient is the client API for ClusterProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClusterProxyClient interface {
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpRequest], error)
	SendResponse(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HttpResponse, SendResponseResult], error)
}

type clusterProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewClusterProxyClient(cc grpc.ClientConnInterface) ClusterProxyClient {
	return &clusterProxyClient{cc}
}

func (c *clusterProxyClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HttpRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterProxy_ServiceDesc.Streams[0], ClusterProxy_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, HttpRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterProxy_SubscribeClient = grpc.ServerStreamingClient[HttpRequest]

func (c *clusterProxyClient) SendResponse(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HttpResponse, SendResponseResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ClusterProxy_ServiceDesc.Streams[1], ClusterProxy_SendResponse_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HttpResponse, SendResponseResult]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterProxy_SendResponseClient = grpc.ClientStreamingClient[HttpResponse, SendResponseResult]

// ClusterProxyServer is the server API for ClusterProxy service.
// All implementations should embed UnimplementedClusterProxyServer
// for forward compatibility.
type ClusterProxyServer interface {
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[HttpRequest]) error
	SendResponse(grpc.ClientStreamingServer[HttpResponse, SendResponseResult]) error
}

// UnimplementedClusterProxyServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClusterProxyServer struct{}

func (UnimplementedClusterProxyServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[HttpRequest]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedClusterProxyServer) SendResponse(grpc.ClientStreamingServer[HttpResponse, SendResponseResult]) error {
	return status.Errorf(codes.Unimplemented, "method SendResponse not implemented")
}
func (UnimplementedClusterProxyServer) testEmbeddedByValue() {}

// UnsafeClusterProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClusterProxyServer will
// result in compilation errors.
type UnsafeClusterProxyServer interface {
	mustEmbedUnimplementedClusterProxyServer()
}

func RegisterClusterProxyServer(s grpc.ServiceRegistrar, srv ClusterProxyServer) {
	// If the following call pancis, it indicates UnimplementedClusterProxyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClusterProxy_ServiceDesc, srv)
}

func _ClusterProxy_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ClusterProxyServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, HttpRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterProxy_SubscribeServer = grpc.ServerStreamingServer[HttpRequest]

func _ClusterProxy_SendResponse_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClusterProxyServer).SendResponse(&grpc.GenericServerStream[HttpResponse, SendResponseResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ClusterProxy_SendResponseServer = grpc.ClientStreamingServer[HttpResponse, SendResponseResult]

// ClusterProxy_ServiceDesc is the grpc.ServiceDesc for ClusterProxy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClusterProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cluster_proxy.v1alpha1.ClusterProxy",
	HandlerType: (*ClusterProxyServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _ClusterProxy_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SendResponse",
			Handler:       _ClusterProxy_SendResponse_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/v1/proxy/proxy.proto",
}
