name: syft-sbom-ci

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Anchore SBOM Action
        uses: anchore/sbom-action@9246b90769f852b3a8921f330c59e0b3f439d6e9 # v0
        with:
          artifact-name: ${{ github.event.repository.name }}-spdx.json
