name: syft-sbom-ci

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Anchore SBOM Action
        uses: anchore/sbom-action@f8bdd1d8ac5e901a77a92f111440fdb1b593736b # v0
        with:
          artifact-name: ${{ github.event.repository.name }}-spdx.json
