name: syft-sbom-ci

on:
  release:
    types: [created]

jobs:
  syft-sbom:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4

      - name: Anchore SBOM Action
        uses: anchore/sbom-action@8e94d75ddd33f69f691467e42275782e4bfefe84 # v0
        with:
          artifact-name: ${{ github.event.repository.name }}-spdx.json
